/**
 * Traducciones manuales (curadas) de nombres ExerciseDB EN -> ES.
 * Prioridad absoluta frente a cualquier traduccion automatica.
 */
export const EXERCISE_NAME_ES_MANUAL: Record<string, string> = {
  '3/4 sit-up': 'Abdominal 3/4',
  '45° side bend': 'Flexion lateral 45 grados',
  'air bike': 'Bicicleta abdominal',
  'all fours squad stretch': 'Estiramiento en cuadrupedia',
  'alternate heel touchers': 'Toques alternos al talon',
  'alternate lateral pulldown': 'Jalon lateral alterno',
  'ankle circles': 'Circulos de tobillo',
  'archer pull up': 'Dominada tipo arquero',
  'archer push up': 'Flexion tipo arquero',
  'arm slingers hanging bent knee legs': 'Colgado con elevacion de rodillas flexionadas',
  'assisted chest dip (kneeling)': 'Fondo de pecho asistido (arrodillado)',
  'assisted motion russian twist': 'Giro ruso asistido',
  'back and forth step': 'Paso adelante y atras',
  'back extension on exercise ball': 'Extension lumbar en fitball',
  'back extension on exercise ball (arms crossed)': 'Extension lumbar en fitball (brazos cruzados)',
  'back extension on exercise ball (arms overhead)': 'Extension lumbar en fitball (brazos arriba)',
  'back extension on exercise ball (hands behind head)': 'Extension lumbar en fitball (manos detras de la cabeza)',
  'back extension on exercise ball (right side)': 'Extension lumbar en fitball (lado derecho)',
  'back extension on exercise ball (left side)': 'Extension lumbar en fitball (lado izquierdo)',
  'band alternating biceps curl': 'Curl de biceps alterno con banda',
  'band alternating reverse curl': 'Curl inverso alterno con banda',
  'band assisted chest dip': 'Fondo de pecho asistido con banda',
  'band assisted pull-up': 'Dominada asistida con banda',
  'band bent-over hip extension': 'Extension de cadera inclinado con banda',
  'band bent-over row': 'Remo inclinado con banda',
  'band biceps curl': 'Curl de biceps con banda',
  'band close-grip pulldown': 'Jalon cerrado con banda',
  'band concentration curl': 'Curl concentrado con banda',
  'band fixed back close grip pulldown': 'Jalon cerrado anclado con banda',
  'band fixed back underhand pulldown': 'Jalon supino anclado con banda',
  'band fixed back v close grip pulldown': 'Jalon en V anclado con banda',
  'band front lateral raise': 'Elevacion frontal-lateral con banda',
  'band front raise': 'Elevacion frontal con banda',
  'band hammer curl': 'Curl martillo con banda',
  'band high hammer curl': 'Curl martillo alto con banda',
  'band hip lift': 'Elevacion de cadera con banda',
  'band horizontal pallof press': 'Pallof press horizontal con banda',
  'band kneeling one arm pulldown': 'Jalon a una mano arrodillado con banda',
  'band kneeling twist': 'Giro arrodillado con banda',
  'band lateral raise': 'Elevacion lateral con banda',
  'band lying hip internal rotation': 'Rotacion interna de cadera tumbado con banda',
  'band lying shoulder internal rotation': 'Rotacion interna de hombro tumbado con banda',
  'band one arm overhead biceps curl': 'Curl de biceps sobre cabeza a una mano con banda',
  'band one arm standing low row': 'Remo bajo de pie a una mano con banda',
  'band one arm twisting chest press': 'Press de pecho con giro a una mano con banda',
  'band one arm twisting seated row': 'Remo sentado con giro a una mano con banda',
  'band pull apart': 'Apertura de banda',
  'band pull through': 'Pull-through con banda',
  'band reverse wrist curl': 'Curl de muneca inverso con banda',
  'band seated row': 'Remo sentado con banda',
  'band shoulder press': 'Press de hombro con banda',
  'band side triceps extension': 'Extension de triceps lateral con banda',
  'band squat': 'Sentadilla con banda',
  'band standing crunch': 'Crunch de pie con banda',
  'band standing rear delt row': 'Remo deltoide posterior de pie con banda',
  'band standing twist': 'Giro de pie con banda',
  'band straight back stiff leg deadlift': 'Peso muerto rumano con banda',
  'band straight leg deadlift': 'Peso muerto con piernas rectas con banda',
  'band triceps kickback': 'Patada de triceps con banda',
  'band underhand pulldown': 'Jalon supino con banda',
  'band upright row': 'Remo al menton con banda',
  'band wrist curl': 'Curl de muneca con banda',
  'barbell bench front squat': 'Sentadilla frontal tipo Zercher con barra',
  'barbell bench press': 'Press de banca con barra',
  'barbell bent over row': 'Remo inclinado con barra',
  'barbell biceps curl': 'Curl de biceps con barra',
  'barbell clean and press': 'Cargada y press con barra',
  'barbell deadlift': 'Peso muerto con barra',
  'barbell decline bench press': 'Press de banca declinado con barra',
  'barbell front raise': 'Elevacion frontal con barra',
  'barbell front squat': 'Sentadilla frontal con barra',
  'barbell full squat': 'Sentadilla profunda con barra',
  'barbell glute bridge': 'Puente de gluteo con barra',
  'barbell hack squat': 'Hack squat con barra',
  'barbell incline bench press': 'Press inclinado con barra',
  'barbell incline row': 'Remo inclinado en banco con barra',
  'barbell lunge': 'Zancada con barra',
  'barbell overhead squat': 'Sentadilla por encima de la cabeza con barra',
  'barbell preacher curl': 'Curl predicador con barra',
  'barbell pull over': 'Pullover con barra',
  'barbell reverse curl': 'Curl inverso con barra',
  'barbell reverse grip bent over row': 'Remo inclinado supino con barra',
  'barbell romanian deadlift': 'Peso muerto rumano con barra',
  'barbell seated calf raise': 'Gemelo sentado con barra',
  'barbell shoulder press': 'Press militar con barra',
  'barbell shrug': 'Encogimientos con barra',
  'barbell squat': 'Sentadilla con barra',
  'barbell standing calf raise': 'Gemelo de pie con barra',
  'barbell standing close grip military press': 'Press militar cerrado de pie con barra',
  'barbell standing wide military press': 'Press militar abierto de pie con barra',
  'barbell upright row': 'Remo al menton con barra',
  'barbell wrist curl': 'Curl de muneca con barra',
  'bodyweight squat': 'Sentadilla con peso corporal',
  'burpee': 'Burpee',
  'cable crunch': 'Crunch en polea',
  'cable crossover': 'Cruce en polea',
  'cable face pull': 'Face pull en polea',
  'cable front raise': 'Elevacion frontal en polea',
  'cable hip abduction': 'Abduccion de cadera en polea',
  'cable hip adduction': 'Aduccion de cadera en polea',
  'cable lateral raise': 'Elevacion lateral en polea',
  'cable one arm triceps extension': 'Extension de triceps a una mano en polea',
  'cable pushdown': 'Jalon de triceps en polea',
  'cable reverse fly': 'Aperturas inversas en polea',
  'cable row': 'Remo en polea',
  'cable seated row': 'Remo sentado en polea',
  'cable triceps pushdown': 'Jalon de triceps en polea',
  'chin-up': 'Dominada supina',
  'close-grip push-up': 'Flexion con agarre cerrado',
  'crunch': 'Crunch',
  'dead bug': 'Dead bug',
  'decline push-up': 'Flexion declinada',
  'dips': 'Fondos',
  'dumbbell bench press': 'Press de banca con mancuernas',
  'dumbbell biceps curl': 'Curl de biceps con mancuernas',
  'dumbbell chest fly': 'Aperturas con mancuernas',
  'dumbbell deadlift': 'Peso muerto con mancuernas',
  'dumbbell front raise': 'Elevacion frontal con mancuernas',
  'dumbbell hammer curl': 'Curl martillo con mancuernas',
  'dumbbell incline bench press': 'Press inclinado con mancuernas',
  'dumbbell lateral raise': 'Elevacion lateral con mancuernas',
  'dumbbell lunge': 'Zancada con mancuernas',
  'dumbbell pullover': 'Pullover con mancuerna',
  'dumbbell reverse fly': 'Aperturas inversas con mancuernas',
  'dumbbell row': 'Remo con mancuerna',
  'dumbbell shoulder press': 'Press de hombro con mancuernas',
  'dumbbell squat': 'Sentadilla con mancuernas',
  'dumbbell triceps extension': 'Extension de triceps con mancuerna',
  'face pull': 'Face pull',
  'front plank': 'Plancha frontal',
  'glute bridge': 'Puente de gluteos',
  'hammer curl': 'Curl martillo',
  'hanging leg raise': 'Elevacion de piernas colgado',
  'hip thrust': 'Hip thrust',
  'incline push-up': 'Flexion inclinada',
  'jump rope': 'Saltar cuerda',
  'jumping jack': 'Jumping jack',
  'kettlebell swing': 'Swing con kettlebell',
  'lat pulldown': 'Jalon al pecho',
  'leg extension': 'Extension de cuadriceps',
  'leg press': 'Prensa de piernas',
  'leg raise': 'Elevacion de piernas',
  'lunge': 'Zancada',
  'mountain climber': 'Escalador',
  'pull-up': 'Dominada',
  'push-up': 'Flexion',
  'romanian deadlift': 'Peso muerto rumano',
  'russian twist': 'Giro ruso',
  'seated cable row': 'Remo sentado en polea',
  'seated dumbbell shoulder press': 'Press de hombro sentado con mancuernas',
  'shoulder press': 'Press de hombro',
  'side plank': 'Plancha lateral',
  'sit-up': 'Abdominal',
  'squat': 'Sentadilla',
  'step-up': 'Subida al banco',
  'triceps dip': 'Fondo de triceps',
  'triceps extension': 'Extension de triceps',
  'upright row': 'Remo al menton',
  'walking lunge': 'Zancada caminando'
};

