/**
 * Traducciones manuales (curadas) de nombres ExerciseDB EN -> ES.
 * Prioridad absoluta frente a cualquier traduccion automatica.
 */
export const EXERCISE_NAME_ES_MANUAL: Record<string, string> = {
  // --- Basicos / varios ---
  '3/4 sit-up': 'Abdominal 3/4',
  '45° side bend': 'Flexion lateral 45 grados',
  'air bike': 'Bicicleta abdominal',
  'all fours squad stretch': 'Estiramiento en cuadrupedia',
  'alternate heel touchers': 'Toques alternos al talon',
  'alternate lateral pulldown': 'Jalon lateral alterno',
  'ankle circles': 'Circulos de tobillo',
  'archer pull up': 'Dominada tipo arquero',
  'archer push up': 'Flexion tipo arquero',
  'arm slingers hanging bent knee legs': 'Elevacion de rodillas flexionadas colgado',
  'arm slingers hanging straight legs': 'Elevacion de piernas rectas colgado',
  'arms apart circular toe touch (male)': 'Toque circular de puntas con brazos abiertos',
  'arms overhead full sit-up (male)': 'Abdominal completo con brazos arriba',
  'assisted chest dip (kneeling)': 'Fondo de pecho asistido (arrodillado)',
  'assisted hanging knee raise': 'Elevacion de rodillas colgado asistida',
  'assisted hanging knee raise with throw down': 'Elevacion de rodillas colgado asistida con empuje',
  'assisted lying calves stretch': 'Estiramiento de gemelos tumbado asistido',
  'assisted lying glutes stretch': 'Estiramiento de gluteos tumbado asistido',
  'assisted lying gluteus and piriformis stretch': 'Estiramiento de gluteo y piriforme tumbado asistido',
  'assisted lying leg raise with lateral throw down': 'Elevacion lateral de piernas tumbado asistida',
  'assisted lying leg raise with throw down': 'Elevacion de piernas tumbado asistida con empuje',
  'assisted motion russian twist': 'Giro ruso asistido',
  'assisted parallel close grip pull-up': 'Dominada paralela agarre cerrado asistida',
  'assisted prone hamstring': 'Estiramiento isquiotibial prono asistido',
  'assisted prone lying quads stretch': 'Estiramiento de cuadriceps prono asistido',
  'assisted prone rectus femoris stretch': 'Estiramiento del recto femoral prono asistido',
  'assisted pull-up': 'Dominada asistida',
  'assisted seated pectoralis major stretch with stability ball': 'Estiramiento del pectoral mayor sentado con fitball',
  'assisted side lying adductor stretch': 'Estiramiento de aductor lateral tumbado asistido',
  'assisted sit-up': 'Abdominal asistido',
  'assisted standing chin-up': 'Dominada supina asistida de pie',
  'assisted standing pull-up': 'Dominada asistida de pie',
  'assisted standing triceps extension (with towel)': 'Extension de triceps asistida de pie (con toalla)',
  'assisted triceps dip (kneeling)': 'Fondo de triceps asistido (arrodillado)',
  'assisted wide-grip chest dip (kneeling)': 'Fondo de pecho agarre ancho asistido (arrodillado)',
  'astride jumps (male)': 'Saltos con piernas abiertas',
  // --- B ---
  'back and forth step': 'Paso adelante y atras',
  'back extension on exercise ball': 'Extension lumbar en fitball',
  'back extension on exercise ball (arms crossed)': 'Extension lumbar en fitball (brazos cruzados)',
  'back extension on exercise ball (arms overhead)': 'Extension lumbar en fitball (brazos arriba)',
  'back extension on exercise ball (hands behind head)': 'Extension lumbar en fitball (manos detras cabeza)',
  'back extension on exercise ball (right side)': 'Extension lumbar en fitball (lado derecho)',
  'back extension on exercise ball (left side)': 'Extension lumbar en fitball (lado izquierdo)',
  'back lever': 'Palanca trasera',
  'back pec stretch': 'Estiramiento de pectoral trasero',
  'backward jump': 'Salto hacia atras',
  'balance board': 'Balance en tabla de equilibrio',
  // --- Banda elastica ---
  'band alternating biceps curl': 'Curl de biceps alterno con banda',
  'band alternating reverse curl': 'Curl inverso alterno con banda',
  'band alternating v-up': 'V-up alterno con banda',
  'band assisted chest dip': 'Fondo de pecho asistido con banda',
  'band assisted pull-up': 'Dominada asistida con banda',
  'band assisted wheel rollerout': 'Rueda abdominal asistida con banda',
  'band bench press': 'Press de banca con banda',
  'band bent-over hip extension': 'Extension de cadera inclinado con banda',
  'band bent-over row': 'Remo inclinado con banda',
  'band bicycle crunch': 'Crunch bicicleta con banda',
  'band biceps curl': 'Curl de biceps con banda',
  'band close-grip pulldown': 'Jalon cerrado con banda',
  'band close-grip push-up': 'Flexion agarre cerrado con banda',
  'band concentration curl': 'Curl concentrado con banda',
  'band fixed back close grip pulldown': 'Jalon cerrado anclado con banda',
  'band fixed back underhand pulldown': 'Jalon supino anclado con banda',
  'band fixed back v close grip pulldown': 'Jalon en V anclado con banda',
  'band front lateral raise': 'Elevacion frontal-lateral con banda',
  'band front raise': 'Elevacion frontal con banda',
  'band hammer curl': 'Curl martillo con banda',
  'band high hammer curl': 'Curl martillo alto con banda',
  'band hip lift': 'Elevacion de cadera con banda',
  'band horizontal pallof press': 'Pallof press horizontal con banda',
  'band jack knife sit-up': 'Navaja abdominal con banda',
  'band kneeling one arm pulldown': 'Jalon a un brazo arrodillado con banda',
  'band kneeling twist': 'Giro arrodillado con banda',
  'band kneeling twisting crunch': 'Crunch con giro arrodillado con banda',
  'band lateral raise': 'Elevacion lateral con banda',
  'band lying hip internal rotation': 'Rotacion interna de cadera tumbado con banda',
  'band lying shoulder internal rotation': 'Rotacion interna de hombro tumbado con banda',
  'band lying straight leg raise': 'Elevacion de piernas rectas tumbado con banda',
  'band one arm overhead biceps curl': 'Curl de biceps sobre cabeza a un brazo con banda',
  'band one arm single leg split squat': 'Sentadilla split a una pierna a un brazo con banda',
  'band one arm standing low row': 'Remo bajo de pie a un brazo con banda',
  'band one arm twisting chest press': 'Press de pecho con giro a un brazo con banda',
  'band one arm twisting seated row': 'Remo sentado con giro a un brazo con banda',
  'band pull apart': 'Apertura de banda',
  'band pull through': 'Pull-through con banda',
  'band push sit-up': 'Abdominal con empuje con banda',
  'band reverse fly': 'Aperturas inversas con banda',
  'band reverse wrist curl': 'Curl de muneca inverso con banda',
  'band seated hip internal rotation': 'Rotacion interna de cadera sentado con banda',
  'band seated row': 'Remo sentado con banda',
  'band seated twist': 'Giro sentado con banda',
  'band shoulder press': 'Press de hombro con banda',
  'band shrug': 'Encogimientos con banda',
  'band side triceps extension': 'Extension lateral de triceps con banda',
  'band single leg calf raise': 'Gemelo a una pierna con banda',
  'band single leg reverse calf raise': 'Gemelo inverso a una pierna con banda',
  'band single leg split squat': 'Sentadilla split a una pierna con banda',
  'band squat': 'Sentadilla con banda',
  'band squat row': 'Remo en sentadilla con banda',
  'band standing crunch': 'Crunch de pie con banda',
  'band standing rear delt row': 'Remo deltoide posterior de pie con banda',
  'band standing twisting crunch': 'Crunch con giro de pie con banda',
  'band step-up': 'Subida al banco con banda',
  'band stiff leg deadlift': 'Peso muerto con piernas rigidas con banda',
  'band straight back stiff leg deadlift': 'Peso muerto rumano espalda recta con banda',
  'band straight leg deadlift': 'Peso muerto piernas rectas con banda',
  'band triceps kickback': 'Patada de triceps con banda',
  'band twisting overhead press': 'Press sobre cabeza con giro con banda',
  'band two legs calf raise - (band under both legs) v. 2': 'Gemelo con dos piernas con banda (v. 2)',
  'band underhand pulldown': 'Jalon supino con banda',
  'band upright row': 'Remo al menton con banda',
  'band v-up': 'V-up con banda',
  'band vertical pallof press': 'Pallof press vertical con banda',
  'band wrist curl': 'Curl de muneca con banda',
  'band y-raise': 'Elevacion en Y con banda',
  // --- Barra (barbell) ---
  'barbell alternate biceps curl': 'Curl de biceps alterno con barra',
  'barbell bench front squat': 'Sentadilla frontal tipo Zercher con barra',
  'barbell bench press': 'Press de banca con barra',
  'barbell bench squat': 'Sentadilla en banco con barra',
  'barbell bent arm pullover': 'Pullover con codos doblados con barra',
  'barbell bent over row': 'Remo inclinado con barra',
  'barbell biceps curl': 'Curl de biceps con barra',
  'barbell biceps curl (with arm blaster)': 'Curl de biceps con barra (arm blaster)',
  'barbell clean and press': 'Cargada y press con barra',
  'barbell clean-grip front squat': 'Sentadilla frontal con agarre de cargada',
  'barbell close-grip bench press': 'Press de banca agarre cerrado con barra',
  'barbell curl': 'Curl con barra',
  'barbell deadlift': 'Peso muerto con barra',
  'barbell decline bench press': 'Press de banca declinado con barra',
  'barbell decline bent arm pullover': 'Pullover declinado con brazos doblados con barra',
  'barbell decline close grip to skull press': 'Skull crusher declinado agarre cerrado con barra',
  'barbell decline pullover': 'Pullover declinado con barra',
  'barbell decline wide-grip press': 'Press declinado agarre ancho con barra',
  'barbell decline wide-grip pullover': 'Pullover declinado agarre ancho con barra',
  'barbell drag curl': 'Curl arrastre con barra',
  'barbell floor calf raise': 'Gemelo en suelo con barra',
  'barbell front chest squat': 'Sentadilla frontal de pecho con barra',
  'barbell front raise': 'Elevacion frontal con barra',
  'barbell front raise and pullover': 'Elevacion frontal y pullover con barra',
  'barbell front squat': 'Sentadilla frontal con barra',
  'barbell full squat': 'Sentadilla profunda con barra',
  'barbell full squat (back pov)': 'Sentadilla profunda con barra (vista trasera)',
  'barbell full squat (side pov)': 'Sentadilla profunda con barra (vista lateral)',
  'barbell full zercher squat': 'Sentadilla Zercher completa con barra',
  'barbell glute bridge': 'Puente de gluteo con barra',
  'barbell glute bridge two legs on bench (male)': 'Puente de gluteo con dos piernas en banco con barra',
  'barbell good morning': 'Buenos dias con barra',
  'barbell guillotine bench press': 'Press guillotina con barra',
  'barbell hack squat': 'Hack squat con barra',
  'barbell high bar squat': 'Sentadilla barra alta',
  'barbell incline bench press': 'Press inclinado con barra',
  'barbell incline close grip bench press': 'Press inclinado agarre cerrado con barra',
  'barbell incline reverse-grip press': 'Press inclinado agarre inverso con barra',
  'barbell incline row': 'Remo inclinado en banco con barra',
  'barbell incline shoulder raise': 'Elevacion de hombro inclinado con barra',
  'barbell jefferson squat': 'Sentadilla Jefferson con barra',
  'barbell jm bench press': 'Press JM en banco con barra',
  'barbell jump squat': 'Sentadilla con salto con barra',
  'barbell lateral lunge': 'Zancada lateral con barra',
  'barbell low bar squat': 'Sentadilla barra baja',
  'barbell lunge': 'Zancada con barra',
  'barbell lying back of the head tricep extension': 'Extension de triceps detras de la cabeza tumbado con barra',
  'barbell lying close-grip press': 'Press cerrado tumbado con barra',
  'barbell lying close-grip triceps extension': 'Extension de triceps cerrada tumbado con barra',
  'barbell lying extension': 'Extension tumbada con barra',
  'barbell lying lifting (on hip)': 'Elevacion de cadera tumbado con barra',
  'barbell lying preacher curl': 'Curl predicador tumbado con barra',
  'barbell lying triceps extension': 'Extension de triceps tumbado con barra',
  'barbell lying triceps extension skull crusher': 'Skull crusher con barra',
  'barbell narrow stance squat': 'Sentadilla pies juntos con barra',
  'barbell one arm bent over row': 'Remo inclinado a un brazo con barra',
  'barbell one arm floor press': 'Press en suelo a un brazo con barra',
  'barbell one arm side deadlift': 'Peso muerto lateral a un brazo con barra',
  'barbell one arm snatch': 'Arrancada a un brazo con barra',
  'barbell one leg squat': 'Sentadilla a una pierna con barra',
  'barbell overhead squat': 'Sentadilla sobre la cabeza con barra',
  'barbell palms down wrist curl over a bench': 'Curl de muneca prono sobre banco con barra',
  'barbell palms up wrist curl over a bench': 'Curl de muneca supino sobre banco con barra',
  'barbell pendlay row': 'Remo Pendlay con barra',
  'barbell pin presses': 'Press desde pines con barra',
  'barbell preacher curl': 'Curl predicador con barra',
  'barbell press sit-up': 'Abdominal con press de barra',
  'barbell prone incline curl': 'Curl inclinado prono con barra',
  'barbell pull over': 'Pullover con barra',
  'barbell pullover': 'Pullover con barra',
  'barbell pullover to press': 'Pullover a press con barra',
  'barbell rack pull': 'Rack pull con barra',
  'barbell rear delt raise': 'Elevacion de deltoide posterior con barra',
  'barbell rear delt row': 'Remo de deltoide posterior con barra',
  'barbell rear lunge': 'Zancada trasera con barra',
  'barbell rear lunge v. 2': 'Zancada trasera con barra (v. 2)',
  'barbell reverse close-grip bench press': 'Press de banca agarre inverso cerrado con barra',
  'barbell reverse curl': 'Curl inverso con barra',
  'barbell reverse grip bent over row': 'Remo inclinado supino con barra',
  'barbell reverse grip decline bench press': 'Press declinado supino con barra',
  'barbell reverse grip incline bench press': 'Press inclinado supino con barra',
  'barbell reverse grip incline bench row': 'Remo inclinado supino en banco con barra',
  'barbell reverse grip skullcrusher': 'Skull crusher supino con barra',
  'barbell reverse preacher curl': 'Curl predicador inverso con barra',
  'barbell reverse wrist curl': 'Curl de muneca inverso con barra',
  'barbell reverse wrist curl v. 2': 'Curl de muneca inverso con barra (v. 2)',
  'barbell rollerout': 'Rueda abdominal con barra',
  'barbell rollerout from bench': 'Rueda abdominal desde banco con barra',
  'barbell romanian deadlift': 'Peso muerto rumano con barra',
  'barbell seated behind head military press': 'Press militar detras de la cabeza sentado con barra',
  'barbell seated bradford rocky press': 'Press Bradford sentado con barra',
  'barbell seated calf raise': 'Gemelo sentado con barra',
  'barbell seated close grip behind neck triceps extension': 'Extension de triceps detras del cuello agarre cerrado sentado',
  'barbell seated close-grip concentration curl': 'Curl concentrado agarre cerrado sentado con barra',
  'barbell seated good morning': 'Buenos dias sentado con barra',
  'barbell seated overhead press': 'Press militar sentado con barra',
  'barbell seated overhead triceps extension': 'Extension de triceps sobre la cabeza sentado con barra',
  'barbell seated twist': 'Giro sentado con barra',
  'barbell shoulder press': 'Press de hombro con barra',
  'barbell shrug': 'Encogimientos con barra',
  'barbell side bent v. 2': 'Flexion lateral con barra (v. 2)',
  'barbell side split squat': 'Sentadilla split lateral con barra',
  'barbell side split squat v. 2': 'Sentadilla split lateral con barra (v. 2)',
  'barbell single leg deadlift': 'Peso muerto a una pierna con barra',
  'barbell single leg split squat': 'Sentadilla split a una pierna con barra',
  'barbell sitted alternate leg raise': 'Elevacion alterna de piernas sentado con barra',
  'barbell sitted alternate leg raise (female)': 'Elevacion alterna de piernas sentado con barra (mujer)',
  'barbell skier': 'Esquiador con barra',
  'barbell speed squat': 'Sentadilla explosiva con barra',
  'barbell split squat v. 2': 'Sentadilla split con barra (v. 2)',
  'barbell squat': 'Sentadilla con barra',
  'barbell squat (on knees)': 'Sentadilla de rodillas con barra',
  'barbell squat jump step rear lunge': 'Sentadilla con salto y zancada trasera con barra',
  'barbell standing ab rollerout': 'Rueda abdominal de pie con barra',
  'barbell standing back wrist curl': 'Curl de muneca trasero de pie con barra',
  'barbell standing bradford press': 'Press Bradford de pie con barra',
  'barbell standing calf raise': 'Gemelo de pie con barra',
  'barbell standing close grip curl': 'Curl agarre cerrado de pie con barra',
  'barbell standing close grip military press': 'Press militar agarre cerrado de pie con barra',
  'barbell standing concentration curl': 'Curl concentrado de pie con barra',
  'barbell standing front raise over head': 'Elevacion frontal sobre la cabeza de pie con barra',
  'barbell standing leg calf raise': 'Gemelo de pie con barra',
  'barbell standing overhead triceps extension': 'Extension de triceps sobre la cabeza de pie con barra',
  'barbell standing reverse grip curl': 'Curl supino de pie con barra',
  'barbell standing rocking leg calf raise': 'Gemelo oscilante de pie con barra',
  'barbell standing twist': 'Giro de pie con barra',
  'barbell standing wide grip biceps curl': 'Curl de biceps agarre ancho de pie con barra',
  'barbell standing wide military press': 'Press militar ancho de pie con barra',
  'barbell standing wide-grip curl': 'Curl agarre ancho de pie con barra',
  'barbell step-up': 'Subida al banco con barra',
  'barbell stiff leg good morning': 'Buenos dias piernas rigidas con barra',
  'barbell straight leg deadlift': 'Peso muerto piernas rectas con barra',
  'barbell sumo deadlift': 'Peso muerto sumo con barra',
  'barbell thruster': 'Thruster con barra',
  'barbell upright row': 'Remo al menton con barra',
  'barbell upright row v. 2': 'Remo al menton con barra (v. 2)',
  'barbell upright row v. 3': 'Remo al menton con barra (v. 3)',
  'barbell wide bench press': 'Press de banca ancho con barra',
  'barbell wide reverse grip bench press': 'Press de banca ancho supino con barra',
  'barbell wide squat': 'Sentadilla ancha con barra',
  'barbell wide-grip upright row': 'Remo al menton agarre ancho con barra',
  'barbell wrist curl': 'Curl de muneca con barra',
  'barbell wrist curl v. 2': 'Curl de muneca con barra (v. 2)',
  'barbell zercher squat': 'Sentadilla Zercher con barra',
  'basic toe touch (male)': 'Toque de punta de pie basico',
  'battling ropes': 'Cuerdas de batalla',
  'bear crawl': 'Gateo de oso',
  'behind head chest stretch': 'Estiramiento de pecho con brazos detras de la cabeza',
  'bench dip (knees bent)': 'Fondo en banco (rodillas dobladas)',
  'bench dip on floor': 'Fondo en banco en el suelo',
  'bench hip extension': 'Extension de cadera en banco',
  'bench pull-ups': 'Dominadas en banco',
  'bent knee lying twist (male)': 'Giro tumbado con rodillas dobladas',
  'biceps leg concentration curl': 'Curl concentrado de biceps sobre pierna',
  'biceps narrow pull-ups': 'Dominadas estrechas de biceps',
  'biceps pull-up': 'Dominada de biceps',
  'body-up': 'Body-up',
  'bodyweight drop jump squat': 'Sentadilla con caida y salto',
  'bodyweight incline side plank': 'Plancha lateral inclinada',
  'bodyweight kneeling triceps extension': 'Extension de triceps de rodillas',
  'bodyweight side lying biceps curl': 'Curl de biceps lateral tumbado',
  'bodyweight squat': 'Sentadilla con peso corporal',
  'bodyweight squatting row': 'Remo en sentadilla con peso corporal',
  'bodyweight squatting row (with towel)': 'Remo en sentadilla con toalla',
  'bodyweight standing calf raise': 'Gemelo de pie con peso corporal',
  'bodyweight standing close-grip one arm row': 'Remo cerrado a un brazo de pie',
  'bodyweight standing close-grip row': 'Remo cerrado de pie',
  'bodyweight standing one arm row': 'Remo a un brazo de pie',
  'bodyweight standing one arm row (with towel)': 'Remo a un brazo de pie con toalla',
  'bodyweight standing row': 'Remo de pie con peso corporal',
  'bodyweight standing row (with towel)': 'Remo de pie con toalla',
  'bottoms-up': 'Fondo invertido',
  'box jump down with one leg stabilization': 'Salto desde cajon con estabilizacion a una pierna',
  'bridge - mountain climber (cross body)': 'Puente con escalador cruzado',
  'burpee': 'Burpee',
  'butt-ups': 'Elevacion de gluteos',
  'butterfly yoga pose': 'Postura de mariposa (yoga)',
  // --- Polea (cable) ---
  'cable alternate shoulder press': 'Press de hombro alterno en polea',
  'cable alternate triceps extension': 'Extension de triceps alterna en polea',
  'cable assisted inverse leg curl': 'Curl de pierna invertido asistido en polea',
  'cable bar lateral pulldown': 'Jalon lateral con barra en polea',
  'cable bench press': 'Press de banca en polea',
  'cable close grip curl': 'Curl agarre cerrado en polea',
  'cable concentration curl': 'Curl concentrado en polea',
  'cable concentration extension (on knee)': 'Extension concentrada en rodilla en polea',
  'cable cross-over lateral pulldown': 'Jalon lateral cruzado en polea',
  'cable cross-over reverse fly': 'Aperturas inversas cruzadas en polea',
  'cable cross-over variation': 'Cruce en polea (variante)',
  'cable crossover': 'Cruce en polea',
  'cable curl': 'Curl en polea',
  'cable deadlift': 'Peso muerto en polea',
  'cable decline fly': 'Aperturas declinadas en polea',
  'cable decline one arm press': 'Press declinado a un brazo en polea',
  'cable decline press': 'Press declinado en polea',
  'cable decline seated wide-grip row': 'Remo declinado sentado agarre ancho en polea',
  'cable drag curl': 'Curl arrastre en polea',
  'cable face pull': 'Face pull en polea',
  'cable floor seated wide-grip row': 'Remo sentado en suelo agarre ancho en polea',
  'cable forward raise': 'Elevacion frontal en polea',
  'cable front raise': 'Elevacion frontal en polea',
  'cable front shoulder raise': 'Elevacion frontal de hombro en polea',
  'cable hammer curl (with rope)': 'Curl martillo con cuerda en polea',
  'cable high pulley overhead tricep extension': 'Extension de triceps sobre la cabeza en polea alta',
  'cable high row (kneeling)': 'Remo alto arrodillado en polea',
  'cable hip abduction': 'Abduccion de cadera en polea',
  'cable hip adduction': 'Aduccion de cadera en polea',
  'cable incline bench press': 'Press inclinado en polea',
  'cable incline bench row': 'Remo inclinado en banco en polea',
  'cable incline fly': 'Aperturas inclinadas en polea',
  'cable incline fly (on stability ball)': 'Aperturas inclinadas en fitball en polea',
  'cable incline pushdown': 'Extension descendente inclinada en polea',
  'cable incline triceps extension': 'Extension de triceps inclinada en polea',
  'cable judo flip': 'Lanzamiento de judo en polea',
  'cable kickback': 'Patada de triceps en polea',
  'cable kneeling crunch': 'Crunch arrodillado en polea',
  'cable kneeling rear delt row (with rope) (male)': 'Remo de deltoide posterior arrodillado con cuerda en polea',
  'cable kneeling triceps extension': 'Extension de triceps arrodillado en polea',
  'cable lat pulldown full range of motion': 'Jalon al pecho rango completo en polea',
  'cable lateral pulldown (with rope attachment)': 'Jalon lateral con cuerda en polea',
  'cable lateral pulldown with v-bar': 'Jalon lateral con barra V en polea',
  'cable lateral raise': 'Elevacion lateral en polea',
  'cable low fly': 'Aperturas bajas en polea',
  'cable low seated row': 'Remo bajo sentado en polea',
  'cable lying bicep curl': 'Curl de biceps tumbado en polea',
  'cable lying close-grip curl': 'Curl cerrado tumbado en polea',
  'cable lying extension pullover (with rope attachment)': 'Extension-pullover tumbado con cuerda en polea',
  'cable lying fly': 'Aperturas tumbado en polea',
  'cable lying triceps extension v. 2': 'Extension de triceps tumbado en polea (v. 2)',
  'cable middle fly': 'Aperturas medias en polea',
  'cable one arm bent over row': 'Remo inclinado a un brazo en polea',
  'cable one arm curl': 'Curl a un brazo en polea',
  'cable one arm decline chest fly': 'Apertura declinada a un brazo en polea',
  'cable one arm fly on exercise ball': 'Apertura a un brazo en fitball con polea',
  'cable one arm incline fly on exercise ball': 'Apertura inclinada a un brazo en fitball con polea',
  'cable one arm incline press': 'Press inclinado a un brazo en polea',
  'cable one arm incline press on exercise ball': 'Press inclinado a un brazo en fitball con polea',
  'cable one arm lateral bent-over': 'Elevacion lateral inclinado a un brazo en polea',
  'cable one arm lateral raise': 'Elevacion lateral a un brazo en polea',
  'cable one arm preacher curl': 'Curl predicador a un brazo en polea',
  'cable one arm press on exercise ball': 'Press a un brazo en fitball con polea',
  'cable one arm pulldown': 'Jalon a un brazo en polea',
  'cable one arm reverse preacher curl': 'Curl predicador inverso a un brazo en polea',
  'cable one arm straight back high row (kneeling)': 'Remo alto espalda recta a un brazo arrodillado en polea',
  'cable one arm tricep pushdown': 'Jalon de triceps a un brazo en polea',
  'cable one arm triceps extension': 'Extension de triceps a un brazo en polea',
  'cable overhead curl': 'Curl sobre la cabeza en polea',
  'cable overhead curl on exercise ball': 'Curl sobre la cabeza en fitball con polea',
  'cable overhead triceps extension (rope attachment)': 'Extension de triceps sobre la cabeza con cuerda en polea',
  'cable palm rotational row': 'Remo con rotacion de palma en polea',
  'cable preacher curl': 'Curl predicador en polea',
  'cable press on exercise ball': 'Press en fitball con polea',
  'cable pull through (with rope)': 'Pull-through con cuerda en polea',
  'cable pulldown': 'Jalon en polea',
  'cable pulldown (pro lat bar)': 'Jalon con barra pro en polea',
  'cable pulldown bicep curl': 'Jalon-curl de biceps en polea',
  'cable pushdown': 'Jalon de triceps en polea',
  'cable pushdown (straight arm) v. 2': 'Extension de brazos rectos en polea (v. 2)',
  'cable pushdown (with rope attachment)': 'Jalon de triceps con cuerda en polea',
  'cable rear delt row (stirrups)': 'Remo de deltoide posterior con estribos en polea',
  'cable rear delt row (with rope)': 'Remo de deltoide posterior con cuerda en polea',
  'cable rear drive': 'Empuje trasero en polea',
  'cable rear pulldown': 'Jalon trasero en polea',
  'cable reverse crunch': 'Crunch inverso en polea',
  'cable reverse curl': 'Curl inverso en polea',
  'cable reverse grip triceps pushdown (sz-bar) (with arm blaster)': 'Jalon de triceps supino barra SZ en polea',
  'cable reverse one arm curl': 'Curl inverso a un brazo en polea',
  'cable reverse preacher curl': 'Curl predicador inverso en polea',
  'cable reverse wrist curl': 'Curl de muneca inverso en polea',
  'cable reverse-grip pushdown': 'Jalon de triceps supino en polea',
  'cable reverse-grip straight back seated high row': 'Remo alto sentado espalda recta supino en polea',
  'cable rope crossover seated row': 'Remo sentado cruzado con cuerda en polea',
  'cable rope elevated seated row': 'Remo sentado elevado con cuerda en polea',
  'cable rope extension incline bench row': 'Remo inclinado con cuerda en polea',
  'cable rope hammer preacher curl': 'Curl predicador martillo con cuerda en polea',
  'cable rope high pulley overhead tricep extension': 'Extension de triceps sobre la cabeza con cuerda en polea alta',
  'cable rope incline tricep extension': 'Extension de triceps inclinada con cuerda en polea',
  'cable rope lying on floor tricep extension': 'Extension de triceps en suelo con cuerda en polea',
  'cable rope one arm hammer preacher curl': 'Curl predicador martillo a un brazo con cuerda en polea',
  'cable rope seated row': 'Remo sentado con cuerda en polea',
  'cable row': 'Remo en polea',
  'cable russian twists (on stability ball)': 'Giro ruso en fitball con polea',
  'cable seated chest press': 'Press de pecho sentado en polea',
  'cable seated crunch': 'Crunch sentado en polea',
  'cable seated curl': 'Curl sentado en polea',
  'cable seated high row (v-bar)': 'Remo alto sentado con barra V en polea',
  'cable seated one arm alternate row': 'Remo alternado a un brazo sentado en polea',
  'cable seated one arm concentration curl': 'Curl concentrado a un brazo sentado en polea',
  'cable seated overhead curl': 'Curl sobre la cabeza sentado en polea',
  'cable seated rear lateral raise': 'Elevacion lateral posterior sentado en polea',
  'cable seated row': 'Remo sentado en polea',
  'cable seated shoulder internal rotation': 'Rotacion interna de hombro sentado en polea',
  'cable seated twist': 'Giro sentado en polea',
  'cable seated wide-grip row': 'Remo sentado agarre ancho en polea',
  'cable shoulder press': 'Press de hombro en polea',
  'cable shrug': 'Encogimientos en polea',
  'cable side bend': 'Flexion lateral en polea',
  'cable side bend crunch (bosu ball)': 'Crunch flexion lateral en bosu con polea',
  'cable side crunch': 'Crunch lateral en polea',
  'cable squat row (with rope attachment)': 'Remo en sentadilla con cuerda en polea',
  'cable squatting curl': 'Curl en sentadilla en polea',
  'cable standing back wrist curl': 'Curl de muneca trasero de pie en polea',
  'cable standing calf raise': 'Gemelo de pie en polea',
  'cable standing cross-over high reverse fly': 'Apertura inversa alta cruzada de pie en polea',
  'cable standing crunch': 'Crunch de pie en polea',
  'cable standing crunch (with rope attachment)': 'Crunch de pie con cuerda en polea',
  'cable standing fly': 'Apertura de pie en polea',
  'cable standing hip extension': 'Extension de cadera de pie en polea',
  'cable standing inner curl': 'Curl interno de pie en polea',
  'cable standing lift': 'Elevacion de pie en polea',
  'cable standing one arm triceps extension': 'Extension de triceps a un brazo de pie en polea',
  'cable standing one leg calf raise': 'Gemelo a una pierna de pie en polea',
  'cable standing pulldown (with rope)': 'Jalon de pie con cuerda en polea',
  'cable standing rear delt row (with rope)': 'Remo de deltoide posterior de pie con cuerda en polea',
  'cable standing reverse grip one arm overhead tricep extension': 'Extension de triceps sobre la cabeza supino a un brazo en polea',
  'cable standing row (v-bar)': 'Remo de pie con barra V en polea',
  'cable standing shoulder external rotation': 'Rotacion externa de hombro de pie en polea',
  'cable standing twist row (v-bar)': 'Remo con giro de pie con barra V en polea',
  'cable standing up straight crossovers': 'Cruce de pie recto en polea',
  'cable straight arm pulldown': 'Jalon de brazos rectos en polea',
  'cable straight arm pulldown (with rope)': 'Jalon de brazos rectos con cuerda en polea',
  'cable straight back seated row': 'Remo sentado espalda recta en polea',
  'cable supine reverse fly': 'Apertura inversa supina en polea',
  'cable thibaudeau kayak row': 'Remo kayak Thibaudeau en polea',
  'cable triceps pushdown (v-bar)': 'Jalon de triceps barra V en polea',
  'cable triceps pushdown (v-bar) (with arm blaster)': 'Jalon de triceps barra V arm blaster en polea',
  'cable tuck reverse crunch': 'Crunch inverso agrupado en polea',
  'cable twist': 'Rotacion en polea',
  'cable twist (up-down)': 'Rotacion arriba-abajo en polea',
  'cable twisting pull': 'Jalon con giro en polea',
  'cable two arm curl on incline bench': 'Curl con dos brazos inclinado en polea',
  'cable two arm tricep kickback': 'Patada de triceps con dos brazos en polea',
  'cable underhand pulldown': 'Jalon supino en polea',
  'cable upper chest crossovers': 'Cruce pecho superior en polea',
  'cable upper row': 'Remo superior en polea',
  'cable upright row': 'Remo al menton en polea',
  'cable wide grip rear pulldown behind neck': 'Jalon trasero agarre ancho por detras del cuello en polea',
  'cable wrist curl': 'Curl de muneca en polea',
  'calf push stretch with hands against wall': 'Estiramiento de gemelo con manos en pared',
  'calf stretch with hands against wall': 'Estiramiento de gemelo apoyado en pared',
  'calf stretch with rope': 'Estiramiento de gemelo con cuerda',
  'cambered bar lying row': 'Remo tumbado con barra curva',
  'captains chair straight leg raise': 'Elevacion de piernas rectas en silla capitan',
  'chair leg extended stretch': 'Estiramiento de pierna extendida en silla',
  'chest and front of shoulder stretch': 'Estiramiento de pecho y hombro anterior',
  'chest dip': 'Fondo de pecho',
  'chest dip (on dip-pull-up cage)': 'Fondo de pecho en jaula',
  'chest dip on straight bar': 'Fondo de pecho en barra recta',
  'chest stretch with exercise ball': 'Estiramiento de pecho con fitball',
  'chest tap push-up (male)': 'Flexion con toque de pecho',
  'chin-up': 'Dominada supina',
  'chin-ups (narrow parallel grip)': 'Dominadas agarre estrecho paralelo',
  'circles knee stretch': 'Circulos de estiramiento de rodilla',
  'clap push up': 'Flexion con palmada',
  'clock push-up': 'Flexion en reloj',
  'close grip chin-up': 'Dominada supina agarre cerrado',
  'close-grip push-up': 'Flexion agarre cerrado',
  'close-grip push-up (on knees)': 'Flexion agarre cerrado de rodillas',
  'cocoons': 'Gusano abdominal',
  'crab twist toe touch': 'Toque de punta de cangrejo con giro',
  'cross body crunch': 'Crunch cruzado',
  'crunch': 'Crunch',
  'crunch (hands overhead)': 'Crunch con manos arriba',
  'crunch (on stability ball)': 'Crunch en fitball',
  'crunch (on stability ball, arms straight)': 'Crunch en fitball con brazos rectos',
  'crunch floor': 'Crunch en suelo',
  'curl-up': 'Abdominal parcial',
  'curtsey squat': 'Sentadilla reverencia',
  'cycle cross trainer': 'Bicicleta eliptica',
  // --- D ---
  'dead bug': 'Dead bug',
  'decline crunch': 'Crunch declinado',
  'decline push-up': 'Flexion declinada',
  'decline sit-up': 'Abdominal declinado',
  'deep push up': 'Flexion profunda',
  'diamond push-up': 'Flexion en diamante',
  'donkey calf raise': 'Gemelo burro',
  'drop push up': 'Flexion con caida',
  'dips': 'Fondos en paralelas',
  // --- Mancuerna (dumbbell) ---
  'dumbbell alternate biceps curl': 'Curl de biceps alterno con mancuernas',
  'dumbbell alternate biceps curl (with arm blaster)': 'Curl alterno con mancuernas (arm blaster)',
  'dumbbell alternate hammer preacher curl': 'Curl predicador martillo alterno con mancuernas',
  'dumbbell alternate preacher curl': 'Curl predicador alterno con mancuernas',
  'dumbbell alternate seated hammer curl': 'Curl martillo alterno sentado con mancuernas',
  'dumbbell alternate side press': 'Press lateral alterno con mancuernas',
  'dumbbell alternating bicep curl with leg raised on exercise ball': 'Curl alternado con pierna levantada en fitball',
  'dumbbell alternating seated bicep curl on exercise ball': 'Curl alternado sentado en fitball con mancuernas',
  'dumbbell arnold press': 'Press Arnold con mancuernas',
  'dumbbell arnold press v. 2': 'Press Arnold con mancuernas (v. 2)',
  'dumbbell around pullover': 'Pullover circular con mancuerna',
  'dumbbell bench press': 'Press de banca con mancuernas',
  'dumbbell bench seated press': 'Press sentado en banco con mancuernas',
  'dumbbell bench squat': 'Sentadilla en banco con mancuernas',
  'dumbbell bent over row': 'Remo inclinado con mancuerna',
  'dumbbell bicep curl lunge with bowling motion': 'Curl en zancada con mancuernas',
  'dumbbell bicep curl on exercise ball with leg raised': 'Curl de biceps en fitball con pierna levantada',
  'dumbbell bicep curl with stork stance': 'Curl de biceps en posicion grulla',
  'dumbbell biceps curl': 'Curl de biceps con mancuernas',
  'dumbbell biceps curl (with arm blaster)': 'Curl de biceps con mancuernas (arm blaster)',
  'dumbbell biceps curl reverse': 'Curl de biceps inverso con mancuernas',
  'dumbbell biceps curl squat': 'Sentadilla con curl de biceps con mancuernas',
  'dumbbell biceps curl v sit on bosu ball': 'Curl de biceps V sentado en bosu',
  'dumbbell burpee': 'Burpee con mancuernas',
  'dumbbell chest fly': 'Aperturas de pecho con mancuernas',
  'dumbbell clean': 'Cargada con mancuernas',
  'dumbbell close grip press': 'Press agarre cerrado con mancuernas',
  'dumbbell close-grip press': 'Press agarre cerrado con mancuernas',
  'dumbbell concentration curl': 'Curl concentrado con mancuernas',
  'dumbbell contralateral forward lunge': 'Zancada frontal contralateral con mancuernas',
  'dumbbell cross body hammer curl': 'Curl martillo cruzado con mancuernas',
  'dumbbell cross body hammer curl v. 2': 'Curl martillo cruzado con mancuernas (v. 2)',
  'dumbbell cuban press': 'Press cubano con mancuernas',
  'dumbbell cuban press v. 2': 'Press cubano con mancuernas (v. 2)',
  'dumbbell deadlift': 'Peso muerto con mancuernas',
  'dumbbell decline bench press': 'Press declinado con mancuernas',
  'dumbbell decline fly': 'Apertura declinada con mancuernas',
  'dumbbell decline hammer press': 'Press martillo declinado con mancuernas',
  'dumbbell decline one arm fly': 'Apertura declinada a un brazo con mancuerna',
  'dumbbell decline one arm hammer press': 'Press martillo declinado a un brazo con mancuerna',
  'dumbbell decline shrug': 'Encogimientos declinados con mancuernas',
  'dumbbell decline shrug v. 2': 'Encogimientos declinados con mancuernas (v. 2)',
  'dumbbell decline triceps extension': 'Extension de triceps declinada con mancuernas',
  'dumbbell decline twist fly': 'Apertura declinada con giro con mancuernas',
  'dumbbell finger curls': 'Curl de dedos con mancuernas',
  'dumbbell fly': 'Aperturas con mancuernas',
  'dumbbell fly on exercise ball': 'Aperturas en fitball con mancuernas',
  'dumbbell forward lunge triceps extension': 'Zancada frontal con extension de triceps con mancuernas',
  'dumbbell front raise': 'Elevacion frontal con mancuernas',
  'dumbbell front raise v. 2': 'Elevacion frontal con mancuernas (v. 2)',
  'dumbbell full can lateral raise': 'Elevacion lateral pulgar arriba con mancuernas',
  'dumbbell goblet squat': 'Sentadilla goblet con mancuerna',
  'dumbbell hammer curl': 'Curl martillo con mancuernas',
  'dumbbell hammer curl on exercise ball': 'Curl martillo en fitball con mancuernas',
  'dumbbell hammer curl v. 2': 'Curl martillo con mancuernas (v. 2)',
  'dumbbell hammer curls (with arm blaster)': 'Curl martillo con mancuernas (arm blaster)',
  'dumbbell high curl': 'Curl alto con mancuernas',
  'dumbbell incline alternate press': 'Press inclinado alterno con mancuernas',
  'dumbbell incline bench press': 'Press inclinado con mancuernas',
  'dumbbell incline biceps curl': 'Curl de biceps inclinado con mancuernas',
  'dumbbell incline breeding': 'Apertura inclinada con mancuernas',
  'dumbbell incline curl': 'Curl inclinado con mancuernas',
  'dumbbell incline curl v. 2': 'Curl inclinado con mancuernas (v. 2)',
  'dumbbell incline fly': 'Aperturas inclinadas con mancuernas',
  'dumbbell incline fly on exercise ball': 'Aperturas inclinadas en fitball con mancuernas',
  'dumbbell incline hammer curl': 'Curl martillo inclinado con mancuernas',
  'dumbbell incline hammer press': 'Press martillo inclinado con mancuernas',
  'dumbbell incline hammer press on exercise ball': 'Press martillo inclinado en fitball con mancuernas',
  'dumbbell incline inner biceps curl': 'Curl interno de biceps inclinado con mancuernas',
  'dumbbell incline one arm fly': 'Apertura inclinada a un brazo con mancuerna',
  'dumbbell incline one arm fly on exercise ball': 'Apertura inclinada a un brazo en fitball con mancuerna',
  'dumbbell incline one arm hammer press': 'Press martillo inclinado a un brazo con mancuerna',
  'dumbbell incline one arm hammer press on exercise ball': 'Press martillo inclinado a un brazo en fitball',
  'dumbbell incline one arm lateral raise': 'Elevacion lateral inclinada a un brazo con mancuerna',
  'dumbbell incline one arm press': 'Press inclinado a un brazo con mancuerna',
  'dumbbell incline one arm press on exercise ball': 'Press inclinado a un brazo en fitball con mancuerna',
  'dumbbell incline palm-in press': 'Press inclinado palma hacia dentro con mancuernas',
  'dumbbell incline press on exercise ball': 'Press inclinado en fitball con mancuernas',
  'dumbbell incline raise': 'Elevacion inclinada con mancuernas',
  'dumbbell incline rear lateral raise': 'Elevacion lateral posterior inclinada con mancuernas',
  'dumbbell incline row': 'Remo inclinado con mancuernas',
  'dumbbell incline shoulder raise': 'Elevacion de hombro inclinada con mancuernas',
  'dumbbell incline shrug': 'Encogimientos inclinados con mancuernas',
  'dumbbell incline t-raise': 'Elevacion en T inclinada con mancuernas',
  'dumbbell incline triceps extension': 'Extension de triceps inclinada con mancuernas',
  'dumbbell incline twisted flyes': 'Aperturas inclinadas con giro con mancuernas',
  'dumbbell incline two arm extension': 'Extension con dos brazos inclinada con mancuernas',
  'dumbbell incline y-raise': 'Elevacion en Y inclinada con mancuernas',
  'dumbbell iron cross': 'Cruz de hierro con mancuernas',
  'dumbbell kickback': 'Patada de triceps con mancuerna',
  'dumbbell kickbacks on exercise ball': 'Patada de triceps en fitball con mancuernas',
  'dumbbell kneeling bicep curl exercise ball': 'Curl de biceps arrodillado en fitball con mancuernas',
  'dumbbell lateral raise': 'Elevacion lateral con mancuernas',
  'dumbbell lateral to front raise': 'Elevacion lateral a frontal con mancuernas',
  'dumbbell lunge': 'Zancada con mancuernas',
  'dumbbell lunge with bicep curl': 'Zancada con curl de biceps con mancuernas',
  'dumbbell lying alternate extension': 'Extension alterna tumbada con mancuernas',
  'dumbbell lying elbow press': 'Press de codos tumbado con mancuernas',
  'dumbbell lying extension (across face)': 'Extension tumbada sobre la cara con mancuernas',
  'dumbbell lying external shoulder rotation': 'Rotacion externa de hombro tumbado con mancuernas',
  'dumbbell lying femoral': 'Curl femoral tumbado con mancuerna',
  'dumbbell lying hammer press': 'Press martillo tumbado con mancuernas',
  'dumbbell lying on floor rear delt raise': 'Elevacion de deltoide posterior tumbado en suelo con mancuernas',
  'dumbbell lying one arm deltoid rear': 'Elevacion de deltoide posterior a un brazo tumbado',
  'dumbbell lying one arm press': 'Press a un brazo tumbado con mancuerna',
  'dumbbell lying one arm press v. 2': 'Press a un brazo tumbado con mancuerna (v. 2)',
  'dumbbell lying one arm pronated triceps extension': 'Extension de triceps pronada a un brazo tumbado',
  'dumbbell lying one arm rear lateral raise': 'Elevacion lateral posterior a un brazo tumbado',
  'dumbbell lying one arm supinated triceps extension': 'Extension de triceps supinada a un brazo tumbado',
  'dumbbell lying pronation': 'Pronacion tumbado con mancuernas',
  'dumbbell lying pronation on floor': 'Pronacion tumbado en suelo con mancuernas',
  'dumbbell lying pullover on exercise ball': 'Pullover tumbado en fitball con mancuerna',
  'dumbbell lying rear delt row': 'Remo de deltoide posterior tumbado con mancuernas',
  'dumbbell lying rear lateral raise': 'Elevacion lateral posterior tumbado con mancuernas',
  'dumbbell lying single extension': 'Extension individual tumbado con mancuerna',
  'dumbbell lying supination': 'Supinacion tumbado con mancuernas',
  'dumbbell lying supination on floor': 'Supinacion tumbado en suelo con mancuernas',
  'dumbbell lying supine biceps curl': 'Curl de biceps supino tumbado con mancuernas',
  'dumbbell lying supine curl': 'Curl supino tumbado con mancuernas',
  'dumbbell lying triceps extension': 'Extension de triceps tumbado con mancuernas',
  'dumbbell lying wide curl': 'Curl ancho tumbado con mancuernas',
  'dumbbell neutral grip bench press': 'Press de banca agarre neutro con mancuernas',
  'dumbbell one arm bench fly': 'Apertura en banco a un brazo con mancuerna',
  'dumbbell one arm bent-over row': 'Remo inclinado a un brazo con mancuerna',
  'dumbbell one arm chest fly on exercise ball': 'Apertura de pecho a un brazo en fitball',
  'dumbbell one arm concentration curl (on stability ball)': 'Curl concentrado a un brazo en fitball',
  'dumbbell one arm decline chest press': 'Press de pecho declinado a un brazo con mancuerna',
  'dumbbell one arm fly on exercise ball': 'Apertura a un brazo en fitball con mancuerna',
  'dumbbell one arm french press on exercise ball': 'Press frances a un brazo en fitball',
  'dumbbell one arm hammer preacher curl': 'Curl predicador martillo a un brazo con mancuerna',
  'dumbbell one arm hammer press on exercise ball': 'Press martillo a un brazo en fitball',
  'dumbbell one arm incline chest press': 'Press de pecho inclinado a un brazo con mancuerna',
  'dumbbell one arm kickback': 'Patada de triceps a un brazo con mancuerna',
  'dumbbell one arm lateral raise': 'Elevacion lateral a un brazo con mancuerna',
  'dumbbell one arm lateral raise with support': 'Elevacion lateral a un brazo con soporte',
  'dumbbell one arm press on exercise ball': 'Press a un brazo en fitball con mancuerna',
  'dumbbell one arm prone curl': 'Curl prono a un brazo con mancuerna',
  'dumbbell one arm prone hammer curl': 'Curl martillo prono a un brazo con mancuerna',
  'dumbbell one arm pullover on exercise ball': 'Pullover a un brazo en fitball con mancuerna',
  'dumbbell one arm reverse fly (with support)': 'Apertura inversa a un brazo con soporte',
  'dumbbell one arm reverse grip press': 'Press agarre inverso a un brazo con mancuerna',
  'dumbbell one arm reverse preacher curl': 'Curl predicador inverso a un brazo con mancuerna',
  'dumbbell one arm reverse spider curl': 'Curl arana inverso a un brazo con mancuerna',
  'dumbbell one arm reverse wrist curl': 'Curl de muneca inverso a un brazo con mancuerna',
  'dumbbell one arm seated bicep curl on exercise ball': 'Curl de biceps sentado a un brazo en fitball',
  'dumbbell one arm seated hammer curl': 'Curl martillo sentado a un brazo con mancuerna',
  'dumbbell one arm seated neutral wrist curl': 'Curl de muneca neutro sentado a un brazo',
  'dumbbell one arm shoulder press': 'Press de hombro a un brazo con mancuerna',
  'dumbbell one arm shoulder press v. 2': 'Press de hombro a un brazo con mancuerna (v. 2)',
  'dumbbell one arm snatch': 'Arrancada a un brazo con mancuerna',
  'dumbbell one arm standing curl': 'Curl de pie a un brazo con mancuerna',
  'dumbbell one arm standing hammer curl': 'Curl martillo de pie a un brazo con mancuerna',
  'dumbbell one arm triceps extension (on bench)': 'Extension de triceps a un brazo en banco',
  'dumbbell one arm upright row': 'Remo al menton a un brazo con mancuerna',
  'dumbbell one arm wrist curl': 'Curl de muneca a un brazo con mancuerna',
  'dumbbell one arm zottman preacher curl': 'Curl predicador Zottman a un brazo con mancuerna',
  'dumbbell one leg fly on exercise ball': 'Apertura a una pierna en fitball con mancuerna',
  'dumbbell over bench neutral wrist curl': 'Curl de muneca neutro sobre banco con mancuerna',
  'dumbbell over bench one arm neutral wrist curl': 'Curl de muneca neutro a un brazo sobre banco',
  'dumbbell over bench one arm reverse wrist curl': 'Curl de muneca inverso a un brazo sobre banco',
  'dumbbell over bench one arm wrist curl': 'Curl de muneca a un brazo sobre banco',
  'dumbbell over bench reverse wrist curl': 'Curl de muneca inverso sobre banco con mancuerna',
  'dumbbell over bench wrist curl': 'Curl de muneca sobre banco con mancuerna',
  'dumbbell palm rotational bent over row': 'Remo inclinado con rotacion de palma con mancuernas',
  'dumbbell palms in incline bench press': 'Press inclinado palmas hacia dentro con mancuernas',
  'dumbbell plyo squat': 'Sentadilla pliometrica con mancuernas',
  'dumbbell preacher curl': 'Curl predicador con mancuernas',
  'dumbbell preacher curl over exercise ball': 'Curl predicador sobre fitball con mancuernas',
  'dumbbell preacher hammer curl': 'Curl predicador martillo con mancuernas',
  'dumbbell press on exercise ball': 'Press en fitball con mancuernas',
  'dumbbell pronate-grip triceps extension': 'Extension de triceps agarre pronado con mancuernas',
  'dumbbell prone incline curl': 'Curl inclinado prono con mancuernas',
  'dumbbell prone incline hammer curl': 'Curl martillo inclinado prono con mancuernas',
  'dumbbell pullover': 'Pullover con mancuerna',
  'dumbbell pullover hip extension on exercise ball': 'Pullover con extension de cadera en fitball',
  'dumbbell pullover on exercise ball': 'Pullover en fitball con mancuerna',
  'dumbbell push press': 'Push press con mancuernas',
  'dumbbell raise': 'Elevacion con mancuernas',
  'dumbbell rear delt raise': 'Elevacion de deltoide posterior con mancuernas',
  'dumbbell rear delt row (shoulder)': 'Remo de deltoide posterior con mancuernas',
  'dumbbell rear fly': 'Apertura posterior con mancuernas',
  'dumbbell rear lateral raise': 'Elevacion lateral posterior con mancuernas',
  'dumbbell rear lateral raise (support head)': 'Elevacion lateral posterior con cabeza apoyada',
  'dumbbell rear lunge': 'Zancada trasera con mancuernas',
  'dumbbell reverse bench press': 'Press de banca inverso con mancuernas',
  'dumbbell reverse fly': 'Aperturas inversas con mancuernas',
  'dumbbell reverse grip biceps curl': 'Curl de biceps agarre inverso con mancuernas',
  'dumbbell reverse grip incline bench one arm row': 'Remo inclinado supino a un brazo con mancuerna',
  'dumbbell reverse grip incline bench two arm row': 'Remo inclinado supino con dos brazos con mancuernas',
  'dumbbell reverse grip row (female)': 'Remo supino con mancuernas (mujer)',
  'dumbbell reverse preacher curl': 'Curl predicador inverso con mancuernas',
  'dumbbell reverse spider curl': 'Curl arana inverso con mancuernas',
  'dumbbell reverse wrist curl': 'Curl de muneca inverso con mancuernas',
  'dumbbell romanian deadlift': 'Peso muerto rumano con mancuernas',
  'dumbbell rotation reverse fly': 'Apertura inversa con rotacion con mancuernas',
  'dumbbell row': 'Remo con mancuerna',
  'dumbbell scott press': 'Press Scott con mancuernas',
  'dumbbell seated alternate front raise': 'Elevacion frontal alterna sentado con mancuernas',
  'dumbbell seated alternate hammer curl on exercise ball': 'Curl martillo alterno sentado en fitball',
  'dumbbell seated alternate press': 'Press alterno sentado con mancuernas',
  'dumbbell seated alternate shoulder': 'Rotacion de hombro alterna sentado con mancuernas',
  'dumbbell seated bench extension': 'Extension sentado en banco con mancuernas',
  'dumbbell seated bent arm lateral raise': 'Elevacion lateral con codo doblado sentado con mancuernas',
  'dumbbell seated bent over alternate kickback': 'Patada alterna inclinado sentado con mancuernas',
  'dumbbell seated bent over triceps extension': 'Extension de triceps inclinado sentado con mancuernas',
  'dumbbell seated bicep curl': 'Curl de biceps sentado con mancuernas',
  'dumbbell seated biceps curl (on stability ball)': 'Curl de biceps sentado en fitball',
  'dumbbell seated biceps curl to shoulder press': 'Curl de biceps a press de hombro sentado',
  'dumbbell seated calf raise': 'Gemelo sentado con mancuernas',
  'dumbbell seated curl': 'Curl sentado con mancuernas',
  'dumbbell seated front raise': 'Elevacion frontal sentado con mancuernas',
  'dumbbell seated hammer curl': 'Curl martillo sentado con mancuernas',
  'dumbbell seated inner biceps curl': 'Curl interno de biceps sentado con mancuernas',
  'dumbbell seated kickback': 'Patada de triceps sentado con mancuernas',
  'dumbbell seated lateral raise': 'Elevacion lateral sentado con mancuernas',
  'dumbbell seated lateral raise v. 2': 'Elevacion lateral sentado con mancuernas (v. 2)',
  'dumbbell seated neutral wrist curl': 'Curl de muneca neutro sentado con mancuernas',
  'dumbbell seated one arm bicep curl on exercise ball with leg raised': 'Curl a un brazo sentado en fitball con pierna levantada',
  'dumbbell seated one arm kickback': 'Patada de triceps sentado a un brazo con mancuerna',
  'dumbbell seated one arm rotate': 'Rotacion de un brazo sentado con mancuerna',
  'dumbbell seated one leg calf raise': 'Gemelo a una pierna sentado con mancuerna',
  'dumbbell seated one leg calf raise - hammer grip': 'Gemelo a una pierna sentado agarre martillo',
  'dumbbell seated one leg calf raise - palm up': 'Gemelo a una pierna sentado palma arriba',
  'dumbbell seated palms up wrist curl': 'Curl de muneca palma arriba sentado con mancuernas',
  'dumbbell seated preacher curl': 'Curl predicador sentado con mancuernas',
  'dumbbell seated reverse grip concentration curl': 'Curl concentrado supino sentado con mancuernas',
  'dumbbell seated reverse grip one arm overhead tricep extension': 'Extension de triceps sobre la cabeza supino a un brazo sentado',
  'dumbbell seated shoulder press': 'Press de hombro sentado con mancuernas',
  'dumbbell seated shoulder press (parallel grip)': 'Press de hombro sentado agarre paralelo con mancuernas',
  'dumbbell seated triceps extension': 'Extension de triceps sentado con mancuernas',
  'dumbbell shrug': 'Encogimientos con mancuernas',
  'dumbbell shoulder press': 'Press de hombro con mancuernas',
  'dumbbell side bend': 'Flexion lateral con mancuerna',
  'dumbbell side lying one hand raise': 'Elevacion lateral tumbado a un brazo con mancuerna',
  'dumbbell side plank with rear fly': 'Plancha lateral con apertura posterior con mancuerna',
  'dumbbell single arm overhead carry': 'Caminata con mancuerna sobre la cabeza',
  'dumbbell single leg calf raise': 'Gemelo a una pierna con mancuerna',
  'dumbbell single leg deadlift': 'Peso muerto a una pierna con mancuernas',
  'dumbbell single leg deadlift with stepbox support': 'Peso muerto a una pierna con apoyo en cajón',
  'dumbbell single leg split squat': 'Sentadilla split a una pierna con mancuernas',
  'dumbbell single leg squat': 'Sentadilla a una pierna con mancuernas',
  'dumbbell squat': 'Sentadilla con mancuernas',
  'dumbbell standing alternate hammer curl and press': 'Curl martillo alterno y press de pie con mancuernas',
  'dumbbell standing alternate overhead press': 'Press alterno sobre la cabeza de pie con mancuernas',
  'dumbbell standing alternate raise': 'Elevacion alterna de pie con mancuernas',
  'dumbbell standing alternating tricep kickback': 'Patada de triceps alterna de pie con mancuernas',
  'dumbbell standing around world': 'Elevacion circular de pie con mancuernas',
  'dumbbell standing bent over one arm triceps extension': 'Extension de triceps a un brazo inclinado de pie',
  'dumbbell standing bent over two arm triceps extension': 'Extension de triceps dos brazos inclinado de pie',
  'dumbbell standing biceps curl': 'Curl de biceps de pie con mancuernas',
  'dumbbell standing calf raise': 'Gemelo de pie con mancuernas',
  'dumbbell standing concentration curl': 'Curl concentrado de pie con mancuernas',
  'dumbbell standing front raise above head': 'Elevacion frontal sobre la cabeza de pie con mancuernas',
  'dumbbell standing inner biceps curl v. 2': 'Curl interno de biceps de pie con mancuernas (v. 2)',
  'dumbbell standing kickback': 'Patada de triceps de pie con mancuernas',
  'dumbbell standing one arm concentration curl': 'Curl concentrado a un brazo de pie con mancuerna',
  'dumbbell standing one arm curl (over incline bench)': 'Curl a un brazo de pie sobre banco inclinado',
  'dumbbell standing one arm curl over incline bench': 'Curl a un brazo de pie sobre banco inclinado',
  'dumbbell standing one arm extension': 'Extension a un brazo de pie con mancuerna',
  'dumbbell standing one arm palm in press': 'Press palma hacia dentro a un brazo de pie',
  'dumbbell standing one arm reverse curl': 'Curl inverso a un brazo de pie con mancuerna',
  'dumbbell standing overhead press': 'Press sobre la cabeza de pie con mancuernas',
  'dumbbell standing palms in press': 'Press con palmas hacia dentro de pie con mancuernas',
  'dumbbell standing preacher curl': 'Curl predicador de pie con mancuernas',
  'dumbbell standing reverse curl': 'Curl inverso de pie con mancuernas',
  'dumbbell standing triceps extension': 'Extension de triceps de pie con mancuernas',
  'dumbbell standing zottman preacher curl': 'Curl predicador Zottman de pie con mancuernas',
  'dumbbell step up single leg balance with bicep curl': 'Subida al banco con equilibrio y curl de biceps',
  'dumbbell step-up': 'Subida al banco con mancuernas',
  'dumbbell step-up lunge': 'Subida al banco con zancada con mancuernas',
  'dumbbell step-up split squat': 'Sentadilla split con subida al banco con mancuernas',
  'dumbbell stiff leg deadlift': 'Peso muerto piernas rigidas con mancuernas',
  'dumbbell straight arm pullover': 'Pullover brazos rectos con mancuerna',
  'dumbbell straight leg deadlift': 'Peso muerto piernas rectas con mancuernas',
  'dumbbell sumo pull through': 'Pull-through sumo con mancuernas',
  'dumbbell supported squat': 'Sentadilla con soporte con mancuernas',
  'dumbbell tate press': 'Press Tate con mancuernas',
  'dumbbell tricep kickback with stork stance': 'Patada de triceps en posicion grulla con mancuernas',
  'dumbbell triceps extension': 'Extension de triceps con mancuerna',
  'dumbbell twisting bench press': 'Press de banca con giro con mancuernas',
  'dumbbell upright row': 'Remo al menton con mancuernas',
  'dumbbell upright row (back pov)': 'Remo al menton con mancuernas (vista trasera)',
  'dumbbell upright shoulder external rotation': 'Rotacion externa de hombro erguido con mancuernas',
  'dumbbell w-press': 'Press W con mancuernas',
  'dumbbell waiter biceps curl': 'Curl de biceps camarero con mancuernas',
  'dumbbell zottman curl': 'Curl Zottman con mancuernas',
  'dumbbell zottman preacher curl': 'Curl predicador Zottman con mancuernas',
  'dumbbells seated triceps extension': 'Extension de triceps sentado con mancuernas',
  'dynamic chest stretch (male)': 'Estiramiento dinamico de pecho',
  // --- E ---
  'elbow dips': 'Fondos con codos',
  'elbow lift - reverse push-up': 'Elevacion de codos - flexion inversa',
  'elbow-to-knee': 'Codo a rodilla',
  'elevator': 'Elevador',
  'exercise ball alternating arm ups': 'Elevacion alterna de brazos en fitball',
  'exercise ball back extension with arms extended': 'Extension lumbar en fitball con brazos extendidos',
  'exercise ball back extension with hands behind head': 'Extension lumbar en fitball manos detras cabeza',
  'exercise ball back extension with knees off ground': 'Extension lumbar en fitball con rodillas despegadas',
  'exercise ball back extension with rotation': 'Extension lumbar con rotacion en fitball',
  'exercise ball dip': 'Fondo en fitball',
  'exercise ball hip flexor stretch': 'Estiramiento de flexor de cadera en fitball',
  'exercise ball hug': 'Abrazo al fitball',
  'exercise ball lat stretch': 'Estiramiento de dorsal en fitball',
  'exercise ball lower back stretch (pyramid)': 'Estiramiento lumbar en fitball (piramide)',
  'exercise ball lying side lat stretch': 'Estiramiento lateral de dorsal tumbado en fitball',
  'exercise ball on the wall calf raise': 'Gemelo con fitball en pared',
  'exercise ball on the wall calf raise (tennis ball between ankles)': 'Gemelo con fitball en pared (pelota entre tobillos)',
  'exercise ball on the wall calf raise (tennis ball between knees)': 'Gemelo con fitball en pared (pelota entre rodillas)',
  'exercise ball one leg prone lower body rotation': 'Rotacion de tren inferior prono a una pierna en fitball',
  'exercise ball one legged diagonal kick hamstring curl': 'Curl femoral diagonal a una pierna en fitball',
  'exercise ball pike push up': 'Flexion en pica con fitball',
  'exercise ball prone leg raise': 'Elevacion de piernas prono en fitball',
  'exercise ball seated hamstring stretch': 'Estiramiento de isquiotibial sentado en fitball',
  'exercise ball seated triceps stretch': 'Estiramiento de triceps sentado en fitball',
  'exercise ball supine triceps extension': 'Extension de triceps supino en fitball',
  // --- EZ bar ---
  'ez bar french press on exercise ball': 'Press frances barra EZ en fitball',
  'ez bar lying bent arms pullover': 'Pullover tumbado con codos doblados barra EZ',
  'ez bar lying close grip triceps extension behind head': 'Extension de triceps cerrada detras de la cabeza barra EZ',
  'ez bar reverse grip bent over row': 'Remo inclinado supino barra EZ',
  'ez bar seated close grip concentration curl': 'Curl concentrado cerrado sentado barra EZ',
  'ez bar standing french press': 'Press frances de pie barra EZ',
  'ez barbell anti gravity press': 'Press antigravedad barra EZ',
  'ez barbell close grip preacher curl': 'Curl predicador cerrado barra EZ',
  'ez barbell close-grip curl': 'Curl agarre cerrado barra EZ',
  'ez barbell curl': 'Curl barra EZ',
  'ez barbell decline close grip face press': 'Press cara declinado cerrado barra EZ',
  'ez barbell decline triceps extension': 'Extension de triceps declinada barra EZ',
  'ez barbell incline triceps extension': 'Extension de triceps inclinada barra EZ',
  'ez barbell jm bench press': 'Press JM barra EZ',
  'ez barbell reverse grip curl': 'Curl supino barra EZ',
  'ez barbell reverse grip preacher curl': 'Curl predicador supino barra EZ',
  'ez barbell seated curls': 'Curls sentado barra EZ',
  'ez barbell seated triceps extension': 'Extension de triceps sentado barra EZ',
  'ez barbell spider curl': 'Curl arana barra EZ',
  'ez-bar biceps curl (with arm blaster)': 'Curl de biceps barra EZ (arm blaster)',
  'ez-bar close-grip bench press': 'Press de banca cerrado barra EZ',
  'ez-barbell standing wide grip biceps curl': 'Curl de biceps ancho de pie barra EZ',
  // --- F ---
  'face pull': 'Face pull',
  'farmers walk': 'Paseo del granjero',
  'finger curls': 'Curl de dedos',
  'flag': 'Bandera',
  'flexion leg sit up (bent knee)': 'Abdominal con pierna doblada',
  'flexion leg sit up (straight arm)': 'Abdominal con brazo recto',
  'floor fly (with barbell)': 'Apertura en suelo con barra',
  'flutter kicks': 'Patadas de aleteo',
  'forward jump': 'Salto hacia adelante',
  'forward lunge (male)': 'Zancada frontal',
  'frankenstein squat': 'Sentadilla Frankenstein',
  'frog crunch': 'Crunch rana',
  'frog planche': 'Plancha rana',
  'front lever': 'Palanca frontal',
  'front lever reps': 'Repeticiones en palanca frontal',
  'front plank': 'Plancha frontal',
  'front plank with twist': 'Plancha frontal con giro',
  'full maltese': 'Cruz maltesa completa',
  'full planche': 'Plancha completa',
  'full planche push-up': 'Flexion en plancha completa',
  // --- G ---
  'gironda sternum chin': 'Dominada esternal Gironda',
  'glute bridge': 'Puente de gluteos',
  'glute bridge march': 'Marcha en puente de gluteos',
  'glute bridge two legs on bench (male)': 'Puente de gluteos con dos piernas en banco',
  'glute-ham raise': 'Extension gluteo-isquiotibial',
  'gorilla chin': 'Dominada gorila',
  'groin crunch': 'Crunch inguinal',
  // --- H ---
  'hack calf raise': 'Gemelo en hack squat',
  'hack one leg calf raise': 'Gemelo a una pierna en hack squat',
  'half knee bends (male)': 'Media sentadilla',
  'half sit-up (male)': 'Abdominal parcial',
  'hammer curl': 'Curl martillo',
  'hamstring stretch': 'Estiramiento de isquiotibial',
  'hands bike': 'Bicicleta de manos',
  'hands clasped circular toe touch (male)': 'Toque de punta circular con manos enlazadas',
  'hands reversed clasped circular toe touch (male)': 'Toque de punta circular con manos enlazadas invertidas',
  'handstand': 'Apoyo de manos invertido',
  'handstand push-up': 'Flexion en apoyo de manos invertido',
  'hanging leg hip raise': 'Elevacion de piernas y cadera colgado',
  'hanging leg raise': 'Elevacion de piernas colgado',
  'hanging oblique knee raise': 'Elevacion oblicua de rodillas colgado',
  'hanging pike': 'Pike colgado',
  'hanging straight leg hip raise': 'Elevacion de cadera con piernas rectas colgado',
  'hanging straight leg raise': 'Elevacion de piernas rectas colgado',
  'hanging straight twisting leg hip raise': 'Elevacion de piernas y cadera con giro colgado',
  'high knee against wall': 'Rodilla alta contra la pared',
  'hip raise (bent knee)': 'Elevacion de cadera (rodilla doblada)',
  'hip thrust': 'Hip thrust',
  'hug knees to chest': 'Abrazo de rodillas al pecho',
  'hyght dumbbell fly': 'Apertura alta con mancuernas',
  'hyperextension': 'Hiperextension',
  'hyperextension (on bench)': 'Hiperextension en banco',
  // --- I ---
  'impossible dips': 'Fondos imposibles',
  'incline push-up': 'Flexion inclinada',
  'incline push-up (on box)': 'Flexion inclinada en cajon',
  'incline close-grip push-up': 'Flexion inclinada agarre cerrado',
  'incline leg hip raise (leg straight)': 'Elevacion de piernas y cadera inclinada con piernas rectas',
  'incline push up depth jump': 'Flexion inclinada con salto en profundidad',
  'incline reverse grip push-up': 'Flexion inclinada agarre inverso',
  'incline scapula push up': 'Flexion inclinada de escapula',
  'incline twisting sit-up': 'Abdominal inclinado con giro',
  'inchworm': 'Gusano',
  'inchworm v. 2': 'Gusano (v. 2)',
  'intermediate hip flexor and quad stretch': 'Estiramiento de flexor de cadera y cuadriceps intermedio',
  'inverse leg curl (bench support)': 'Curl de pierna inverso con apoyo en banco',
  'inverse leg curl (on pull-up cable machine)': 'Curl de pierna inverso en maquina de dominadas',
  'inverted row': 'Remo invertido',
  'inverted row bent knees': 'Remo invertido con rodillas dobladas',
  'inverted row on bench': 'Remo invertido en banco',
  'inverted row v. 2': 'Remo invertido (v. 2)',
  'inverted row with straps': 'Remo invertido con correas',
  'iron cross stretch': 'Estiramiento en cruz de hierro',
  'isometric chest squeeze': 'Isometrico de pecho',
  'isometric wipers': 'Limpiaparabrisas isometrico',
  // --- J ---
  'jack burpee': 'Burpee con salto de tijera',
  'jack jump (male)': 'Salto de tijera',
  'jackknife sit-up': 'Abdominal navaja',
  'janda sit-up': 'Abdominal Janda',
  'jump rope': 'Saltar cuerda',
  'jump squat': 'Sentadilla con salto',
  'jump squat v. 2': 'Sentadilla con salto (v. 2)',
  'jumping jack': 'Jumping jack',
  // --- K (kettlebell) ---
  'kettlebell advanced windmill': 'Molino avanzado con kettlebell',
  'kettlebell alternating hang clean': 'Cargada colgante alterna con kettlebell',
  'kettlebell alternating press': 'Press alterno con kettlebell',
  'kettlebell alternating press on floor': 'Press alterno en suelo con kettlebell',
  'kettlebell alternating renegade row': 'Remo renegado alterno con kettlebell',
  'kettlebell alternating row': 'Remo alterno con kettlebell',
  'kettlebell arnold press': 'Press Arnold con kettlebell',
  'kettlebell bent press': 'Press inclinado con kettlebell',
  'kettlebell bottoms up clean from the hang position': 'Cargada invertida desde colgado con kettlebell',
  'kettlebell double alternating hang clean': 'Cargada colgante doble alterna con kettlebell',
  'kettlebell double jerk': 'Envion doble con kettlebell',
  'kettlebell double push press': 'Push press doble con kettlebell',
  'kettlebell double snatch': 'Arrancada doble con kettlebell',
  'kettlebell double windmill': 'Molino doble con kettlebell',
  'kettlebell extended range one arm press on floor': 'Press a un brazo en rango extendido en suelo con kettlebell',
  'kettlebell figure 8': 'Figura 8 con kettlebell',
  'kettlebell front squat': 'Sentadilla frontal con kettlebell',
  'kettlebell goblet squat': 'Sentadilla goblet con kettlebell',
  'kettlebell hang clean': 'Cargada colgante con kettlebell',
  'kettlebell lunge pass through': 'Zancada con paso de kettlebell',
  'kettlebell one arm clean and jerk': 'Cargada y envion a un brazo con kettlebell',
  'kettlebell one arm floor press': 'Press en suelo a un brazo con kettlebell',
  'kettlebell one arm jerk': 'Envion a un brazo con kettlebell',
  'kettlebell one arm military press to the side': 'Press militar lateral a un brazo con kettlebell',
  'kettlebell one arm push press': 'Push press a un brazo con kettlebell',
  'kettlebell one arm row': 'Remo a un brazo con kettlebell',
  'kettlebell one arm snatch': 'Arrancada a un brazo con kettlebell',
  'kettlebell pirate supper legs': 'Elevacion de piernas pirata con kettlebell',
  'kettlebell pistol squat': 'Sentadilla pistola con kettlebell',
  'kettlebell plyo push-up': 'Flexion pliometrica con kettlebell',
  'kettlebell seated press': 'Press sentado con kettlebell',
  'kettlebell seated two arm military press': 'Press militar dos brazos sentado con kettlebell',
  'kettlebell seesaw press': 'Press sube y baja con kettlebell',
  'kettlebell sumo high pull': 'Remo alto sumo con kettlebell',
  'kettlebell swing': 'Swing con kettlebell',
  'kettlebell thruster': 'Thruster con kettlebell',
  'kettlebell turkish get up (squat style)': 'Turkish get-up con kettlebell (estilo sentadilla)',
  'kettlebell two arm clean': 'Cargada dos brazos con kettlebell',
  'kettlebell two arm military press': 'Press militar dos brazos con kettlebell',
  'kettlebell two arm row': 'Remo dos brazos con kettlebell',
  'kettlebell windmill': 'Molino con kettlebell',
  'kick out sit': 'Sentada con patada',
  'kipping muscle up': 'Muscle-up con impulso',
  'knee touch crunch': 'Crunch con toque de rodilla',
  'kneeling jump squat': 'Sentadilla con salto de rodillas',
  'kneeling lat stretch': 'Estiramiento de dorsal arrodillado',
  'kneeling plank tap shoulder (male)': 'Plancha de rodillas con toque de hombro',
  'kneeling push-up (male)': 'Flexion de rodillas',
  'korean dips': 'Fondos coreanos',
  // --- L ---
  'l-pull-up': 'Dominada en L',
  'l-sit on floor': 'L-sit en suelo',
  'landmine 180': 'Landmine 180',
  'landmine lateral raise': 'Elevacion lateral con landmine',
  'lat pulldown': 'Jalon al pecho',
  'lean planche': 'Plancha inclinada',
  'left hook (boxing)': 'Gancho izquierdo (boxeo)',
  'leg extension': 'Extension de cuadriceps',
  'leg press': 'Prensa de piernas',
  'leg pull in flat bench': 'Elevacion de piernas en banco plano',
  'leg raise': 'Elevacion de piernas',
  'leg up hamstring stretch': 'Estiramiento de isquiotibial con pierna arriba',
  // --- Maquina (lever) ---
  'lever alternate leg press': 'Prensa de piernas alterna en maquina',
  'lever alternating narrow grip seated row': 'Remo sentado estrecho alterno en maquina',
  'lever assisted chin-up': 'Dominada supina asistida en maquina',
  'lever back extension': 'Extension lumbar en maquina',
  'lever bent over row': 'Remo inclinado en maquina',
  'lever bent-over row with v-bar': 'Remo inclinado con barra V en maquina',
  'lever bicep curl': 'Curl de biceps en maquina',
  'lever calf press': 'Prensa de gemelo en maquina',
  'lever chest press': 'Press de pecho en maquina',
  'lever deadlift': 'Peso muerto en maquina',
  'lever decline chest press': 'Press de pecho declinado en maquina',
  'lever donkey calf raise': 'Gemelo burro en maquina',
  'lever front pulldown': 'Jalon frontal en maquina',
  'lever gripless shrug': 'Encogimientos sin agarre en maquina',
  'lever gripless shrug v. 2': 'Encogimientos sin agarre en maquina (v. 2)',
  'lever gripper hands': 'Ejercicio de manos en maquina',
  'lever hammer grip preacher curl': 'Curl predicador martillo en maquina',
  'lever high row': 'Remo alto en maquina',
  'lever hip extension v. 2': 'Extension de cadera en maquina (v. 2)',
  'lever horizontal one leg press': 'Prensa horizontal a una pierna en maquina',
  'lever incline chest press': 'Press de pecho inclinado en maquina',
  'lever incline chest press v. 2': 'Press de pecho inclinado en maquina (v. 2)',
  'lever kneeling leg curl': 'Curl de pierna arrodillado en maquina',
  'lever kneeling twist': 'Giro arrodillado en maquina',
  'lever lateral raise': 'Elevacion lateral en maquina',
  'lever leg extension': 'Extension de cuadriceps en maquina',
  'lever lying leg curl': 'Curl femoral tumbado en maquina',
  'lever lying two-one leg curl': 'Curl femoral tumbado dos a uno en maquina',
  'lever military press': 'Press militar en maquina',
  'lever narrow grip seated row': 'Remo sentado estrecho en maquina',
  'lever one arm bent over row': 'Remo inclinado a un brazo en maquina',
  'lever one arm lateral high row': 'Remo lateral alto a un brazo en maquina',
  'lever one arm lateral wide pulldown': 'Jalon lateral ancho a un brazo en maquina',
  'lever one arm shoulder press': 'Press de hombro a un brazo en maquina',
  'lever overhand triceps dip': 'Fondo de triceps prono en maquina',
  'lever preacher curl': 'Curl predicador en maquina',
  'lever preacher curl v. 2': 'Curl predicador en maquina (v. 2)',
  'lever pullover': 'Pullover en maquina',
  'lever reverse grip lateral pulldown': 'Jalon lateral supino en maquina',
  'lever reverse grip preacher curl': 'Curl predicador supino en maquina',
  'lever reverse grip vertical row': 'Remo vertical supino en maquina',
  'lever reverse hyperextension': 'Hiperextension inversa en maquina',
  'lever reverse t-bar row': 'Remo T-bar inverso en maquina',
  'lever rotary calf': 'Gemelo rotatorio en maquina',
  'lever seated calf press': 'Prensa de gemelo sentado en maquina',
  'lever seated calf raise': 'Gemelo sentado en maquina',
  'lever seated crunch': 'Crunch sentado en maquina',
  'lever seated crunch (chest pad)': 'Crunch sentado con almohadilla en maquina',
  'lever seated crunch v. 2': 'Crunch sentado en maquina (v. 2)',
  'lever seated dip': 'Fondo sentado en maquina',
  'lever seated fly': 'Apertura sentado en maquina',
  'lever seated good morning': 'Buenos dias sentado en maquina',
  'lever seated hip abduction': 'Abduccion de cadera sentado en maquina',
  'lever seated hip adduction': 'Aduccion de cadera sentado en maquina',
  'lever seated leg curl': 'Curl femoral sentado en maquina',
  'lever seated leg raise crunch': 'Crunch con elevacion de piernas sentado en maquina',
  'lever seated reverse fly': 'Apertura posterior sentado en maquina',
  'lever seated reverse fly (parallel grip)': 'Apertura posterior sentado agarre paralelo en maquina',
  'lever seated row': 'Remo sentado en maquina',
  'lever seated squat calf raise on leg press machine': 'Sentadilla-gemelo en prensa de piernas',
  'lever shoulder press': 'Press de hombro en maquina',
  'lever shoulder press v. 2': 'Press de hombro en maquina (v. 2)',
  'lever shoulder press v. 3': 'Press de hombro en maquina (v. 3)',
  'lever shrug': 'Encogimientos en maquina',
  'lever standing calf raise': 'Gemelo de pie en maquina',
  'lever standing chest press': 'Press de pecho de pie en maquina',
  'lever t bar row': 'Remo en T en maquina',
  'lever t-bar reverse grip row': 'Remo en T supino en maquina',
  'lever triceps extension': 'Extension de triceps en maquina',
  'lever unilateral row': 'Remo unilateral en maquina',
  'london bridge': 'Puente de Londres',
  'low glute bridge on floor': 'Puente de gluteos bajo en suelo',
  'lower back curl': 'Curl de espalda baja',
  'lunge': 'Zancada',
  'lunge with jump': 'Zancada con salto',
  'lunge with twist': 'Zancada con giro',
  'lying (side) quads stretch': 'Estiramiento de cuadriceps tumbado de lado',
  'lying elbow to knee': 'Codo a rodilla tumbado',
  'lying leg raise flat bench': 'Elevacion de piernas tumbado en banco plano',
  'lying leg-hip raise': 'Elevacion de piernas y cadera tumbado',
  // --- M ---
  'machine inner chest press': 'Press de pecho interno en maquina',
  'march sit (wall)': 'Marcha sentado en pared',
  'medicine ball catch and overhead throw': 'Recogida y lanzamiento sobre la cabeza con balon medicinal',
  'medicine ball chest pass': 'Pase de pecho con balon medicinal',
  'medicine ball chest push from 3 point stance': 'Empuje de pecho desde tres apoyos con balon medicinal',
  'medicine ball chest push multiple response': 'Empuje de pecho multiple con balon medicinal',
  'medicine ball chest push single response': 'Empuje de pecho simple con balon medicinal',
  'medicine ball chest push with run release': 'Empuje de pecho con carrera con balon medicinal',
  'medicine ball close grip push up': 'Flexion cerrada con balon medicinal',
  'medicine ball overhead slam': 'Golpe sobre la cabeza con balon medicinal',
  'medicine ball supine chest throw': 'Lanzamiento de pecho supino con balon medicinal',
  'mixed grip chin-up': 'Dominada con agarre mixto',
  'modified hindu push-up (male)': 'Flexion hindu modificada',
  'modified push up to lower arms': 'Flexion modificada de descenso a antebrazos',
  'monster walk': 'Caminata monstruo',
  'mountain climber': 'Escalador',
  'muscle up': 'Muscle-up',
  'muscle-up (on vertical bar)': 'Muscle-up en barra vertical',
  // --- N ---
  'narrow push-up on exercise ball': 'Flexion estrecha en fitball',
  'neck side stretch': 'Estiramiento lateral de cuello',
  'negative crunch': 'Crunch negativo',
  // --- O ---
  'oblique crunch v. 2': 'Crunch oblicuo (v. 2)',
  'oblique crunches floor': 'Crunch oblicuo en suelo',
  'olympic barbell hammer curl': 'Curl martillo barra olimpica',
  'olympic barbell triceps extension': 'Extension de triceps barra olimpica',
  'one arm against wall': 'Un brazo contra la pared',
  'one arm chin-up': 'Dominada supina a un brazo',
  'one arm dip': 'Fondo a un brazo',
  'one arm slam (with medicine ball)': 'Golpe a un brazo con balon medicinal',
  'one arm towel row': 'Remo con toalla a un brazo',
  'one leg donkey calf raise': 'Gemelo burro a una pierna',
  'one leg floor calf raise': 'Gemelo en suelo a una pierna',
  'one leg squat': 'Sentadilla a una pierna',
  'otis up': 'Abdominal Otis',
  'outside leg kick push-up': 'Flexion con patada lateral de pierna',
  'overhead triceps stretch': 'Estiramiento de triceps sobre la cabeza',
  // --- P ---
  'pelvic tilt': 'Inclinacion pelvica',
  'pelvic tilt into bridge': 'Inclinacion pelvica en puente',
  'peroneals stretch': 'Estiramiento de peroneos',
  'pike-to-cobra push-up': 'Flexion de pica a cobra',
  'plyo push up': 'Flexion pliometrica',
  'posterior step to overhead reach': 'Paso posterior a alcance sobre la cabeza',
  'posterior tibialis stretch': 'Estiramiento del tibial posterior',
  'potty squat': 'Sentadilla en cuclillas',
  'potty squat with support': 'Sentadilla en cuclillas con apoyo',
  'power clean': 'Cargada de potencia',
  'power point plank': 'Plancha con punto de apoyo',
  'prisoner half sit-up (male)': 'Abdominal parcial con manos en la cabeza',
  'prone twist on stability ball': 'Giro prono en fitball',
  'pull up (neutral grip)': 'Dominada agarre neutro',
  'pull-in (on stability ball)': 'Encogimiento en fitball',
  'pull-up': 'Dominada',
  'push and pull bodyweight': 'Empuje y tiron con peso corporal',
  'push to run': 'Empuje para correr',
  'push up on bosu ball': 'Flexion en bosu',
  'push-up': 'Flexion',
  'push-up (bosu ball)': 'Flexion en bosu',
  'push-up (on stability ball)': 'Flexion en fitball',
  'push-up (wall)': 'Flexion en pared',
  'push-up (wall) v. 2': 'Flexion en pared (v. 2)',
  'push-up close-grip off dumbbell': 'Flexion cerrada sobre mancuerna',
  'push-up inside leg kick': 'Flexion con patada interior de pierna',
  'push-up medicine ball': 'Flexion con balon medicinal',
  'push-up on lower arms': 'Flexion sobre antebrazos',
  'push-up plus': 'Flexion plus',
  'push-up to side plank': 'Flexion a plancha lateral',
  // --- Q ---
  'quads (bodyweight squat)': 'Cuadriceps (sentadilla con peso corporal)',
  'quarter sit-up': 'Cuarto de abdominal',
  'quick feet v. 2': 'Pies rapidos (v. 2)',
  // --- R ---
  'raise single arm push-up': 'Flexion con un brazo elevado',
  'rear decline bridge': 'Puente declinado trasero',
  'rear deltoid stretch': 'Estiramiento de deltoide posterior',
  'rear pull-up': 'Dominada trasera',
  'reclining big toe pose with rope': 'Postura reclinada del dedo gordo con cuerda',
  'resistance band hip thrusts on knees (female)': 'Hip thrust de rodillas con banda (mujer)',
  'resistance band leg extension': 'Extension de cuadriceps con banda',
  'resistance band seated biceps curl': 'Curl de biceps sentado con banda',
  'resistance band seated chest press': 'Press de pecho sentado con banda',
  'resistance band seated hip abduction': 'Abduccion de cadera sentado con banda',
  'resistance band seated shoulder press': 'Press de hombro sentado con banda',
  'resistance band seated straight back row': 'Remo sentado espalda recta con banda',
  'reverse crunch': 'Crunch inverso',
  'reverse dip': 'Fondo inverso',
  'reverse grip machine lat pulldown': 'Jalon al pecho supino en maquina',
  'reverse grip pull-up': 'Dominada agarre inverso',
  'reverse hyper extension (on stability ball)': 'Hiperextension inversa en fitball',
  'reverse hyper on flat bench': 'Hiperextension inversa en banco plano',
  'reverse plank with leg lift': 'Plancha inversa con elevacion de pierna',
  'ring dips': 'Fondos en anillas',
  'rocking frog stretch': 'Estiramiento de rana oscilante',
  'rocky pull-up pulldown': 'Jalon-dominada Rocky',
  'roller back stretch': 'Estiramiento de espalda con rodillo',
  'roller body saw': 'Sierra corporal con rodillo',
  'roller hip lat stretch': 'Estiramiento de cadera y dorsal con rodillo',
  'roller hip stretch': 'Estiramiento de cadera con rodillo',
  'roller reverse crunch': 'Crunch inverso con rodillo',
  'roller seated shoulder flexor depresor retractor': 'Flexor-depresor-retractor de hombro sentado con rodillo',
  'roller seated single leg shoulder flexor depresor retractor': 'Flexor de hombro a una pierna sentado con rodillo',
  'roller side lat stretch': 'Estiramiento lateral de dorsal con rodillo',
  'romanian deadlift': 'Peso muerto rumano',
  'rope climb': 'Trepa a la cuerda',
  'run': 'Carrera',
  'run (equipment)': 'Carrera en maquina',
  'runners stretch': 'Estiramiento de corredor',
  'russian twist': 'Giro ruso',
  // --- S ---
  'scapula dips': 'Fondos de escapula',
  'scapula push-up': 'Flexion de escapula',
  'scapular pull-up': 'Dominada escapular',
  'scissor jumps (male)': 'Saltos de tijera',
  'seated cable row': 'Remo sentado en polea',
  'seated calf stretch (male)': 'Estiramiento de gemelo sentado',
  'seated dumbbell shoulder press': 'Press de hombro sentado con mancuernas',
  'seated glute stretch': 'Estiramiento de gluteo sentado',
  'seated leg raise': 'Elevacion de piernas sentado',
  'seated lower back stretch': 'Estiramiento lumbar sentado',
  'seated piriformis stretch': 'Estiramiento del piriforme sentado',
  'seated side crunch (wall)': 'Crunch lateral sentado en pared',
  'seated wide angle pose sequence': 'Secuencia de angulo ancho sentado',
  'self assisted inverse leg curl': 'Curl de pierna inverso autoasistido',
  'self assisted inverse leg curl (on floor)': 'Curl de pierna inverso autoasistido en suelo',
  'semi squat jump (male)': 'Salto en media sentadilla',
  'short stride run': 'Carrera con zancada corta',
  'shoulder grip pull-up': 'Dominada con agarre de hombros',
  'shoulder press': 'Press de hombro',
  'shoulder tap': 'Toque de hombro',
  'shoulder tap push-up': 'Flexion con toque de hombro',
  'side bridge hip abduction': 'Abduccion de cadera en puente lateral',
  'side bridge v. 2': 'Puente lateral (v. 2)',
  'side hip (on parallel bars)': 'Cadera lateral en paralelas',
  'side hip abduction': 'Abduccion lateral de cadera',
  'side lying floor stretch': 'Estiramiento de suelo tumbado de lado',
  'side lying hip adduction (male)': 'Aduccion de cadera tumbado de lado',
  'side plank': 'Plancha lateral',
  'side plank hip adduction': 'Aduccion de cadera en plancha lateral',
  'side push neck stretch': 'Estiramiento lateral de cuello con empuje',
  'side push-up': 'Flexion lateral',
  'side wrist pull stretch': 'Estiramiento de muneca lateral con traccion',
  'side-to-side chin': 'Barbilla de lado a lado',
  'side-to-side toe touch (male)': 'Toque de punta de pie de lado a lado',
  'single arm push-up': 'Flexion a un brazo',
  'single leg bridge with outstretched leg': 'Puente a una pierna con la otra extendida',
  'single leg calf raise (on a dumbbell)': 'Gemelo a una pierna sobre mancuerna',
  'single leg platform slide': 'Deslizamiento en plataforma a una pierna',
  'single leg squat (pistol) male': 'Sentadilla pistola a una pierna',
  'sissy squat': 'Sentadilla sissy',
  'sit-up': 'Abdominal',
  'sit-up v. 2': 'Abdominal (v. 2)',
  'sit-up with arms on chest': 'Abdominal con brazos cruzados en pecho',
  'skater hops': 'Saltos de patinador',
  'ski ergometer': 'Ergometro de esqui',
  'ski step': 'Paso de esqui',
  'skin the cat': 'Pasada de gato',
  'sled 45 degrees one leg press': 'Prensa 45° a una pierna',
  'sled 45° calf press': 'Prensa de gemelo a 45°',
  'sled 45° leg press': 'Prensa de piernas a 45°',
  'sled 45° leg press (back pov)': 'Prensa de piernas a 45° (vista trasera)',
  'sled 45° leg press (side pov)': 'Prensa de piernas a 45° (vista lateral)',
  'sled 45° leg wide press': 'Prensa de piernas ancha a 45°',
  'sled calf press on leg press': 'Prensa de gemelo en prensa de piernas',
  'sled closer hack squat': 'Hack squat cercano en prensa',
  'sled forward angled calf raise': 'Gemelo en angulo hacia delante en prensa',
  'sled hack squat': 'Hack squat en prensa',
  'sled lying calf press': 'Prensa de gemelo tumbado',
  'sled lying squat': 'Sentadilla tumbada en prensa',
  'sled one leg calf press on leg press': 'Prensa de gemelo a una pierna en prensa',
  'sledge hammer': 'Mazo',
  // --- Smith machine ---
  'smith back shrug': 'Encogimientos traseros en maquina Smith',
  'smith behind neck press': 'Press por detras del cuello en maquina Smith',
  'smith bench press': 'Press de banca en maquina Smith',
  'smith bent knee good morning': 'Buenos dias con rodillas dobladas en maquina Smith',
  'smith bent over row': 'Remo inclinado en maquina Smith',
  'smith chair squat': 'Sentadilla en silla en maquina Smith',
  'smith close-grip bench press': 'Press de banca cerrado en maquina Smith',
  'smith deadlift': 'Peso muerto en maquina Smith',
  'smith decline bench press': 'Press de banca declinado en maquina Smith',
  'smith decline reverse-grip press': 'Press declinado supino en maquina Smith',
  'smith front squat (clean grip)': 'Sentadilla frontal agarre cargada en maquina Smith',
  'smith full squat': 'Sentadilla profunda en maquina Smith',
  'smith hack squat': 'Hack squat en maquina Smith',
  'smith hip raise': 'Elevacion de cadera en maquina Smith',
  'smith incline bench press': 'Press inclinado en maquina Smith',
  'smith incline reverse-grip press': 'Press inclinado supino en maquina Smith',
  'smith incline shoulder raises': 'Elevacion de hombro inclinado en maquina Smith',
  'smith leg press': 'Prensa de piernas en maquina Smith',
  'smith low bar squat': 'Sentadilla barra baja en maquina Smith',
  'smith machine bicep curl': 'Curl de biceps en maquina Smith',
  'smith machine decline close grip bench press': 'Press declinado cerrado en maquina Smith',
  'smith machine incline tricep extension': 'Extension de triceps inclinada en maquina Smith',
  'smith machine reverse decline close grip bench press': 'Press declinado cerrado supino en maquina Smith',
  'smith narrow row': 'Remo estrecho en maquina Smith',
  'smith one arm row': 'Remo a un brazo en maquina Smith',
  'smith one leg floor calf raise': 'Gemelo a una pierna en suelo con maquina Smith',
  'smith rear delt row': 'Remo de deltoide posterior en maquina Smith',
  'smith reverse calf raises': 'Elevacion inversa de gemelos en maquina Smith',
  'smith reverse grip bent over row': 'Remo inclinado supino en maquina Smith',
  'smith reverse-grip press': 'Press supino en maquina Smith',
  'smith seated one leg calf raise': 'Gemelo sentado a una pierna en maquina Smith',
  'smith seated shoulder press': 'Press de hombro sentado en maquina Smith',
  'smith seated wrist curl': 'Curl de muneca sentado en maquina Smith',
  'smith shoulder press': 'Press de hombro en maquina Smith',
  'smith shrug': 'Encogimientos en maquina Smith',
  'smith single leg split squat': 'Sentadilla split a una pierna en maquina Smith',
  'smith sprint lunge': 'Zancada de sprint en maquina Smith',
  'smith squat': 'Sentadilla en maquina Smith',
  'smith standing back wrist curl': 'Curl de muneca trasero de pie en maquina Smith',
  'smith standing behind head military press': 'Press militar detras de la cabeza de pie en maquina Smith',
  'smith standing leg calf raise': 'Gemelo de pie en maquina Smith',
  'smith standing military press': 'Press militar de pie en maquina Smith',
  'smith sumo squat': 'Sentadilla sumo en maquina Smith',
  'smith toe raise': 'Elevacion de punta de pie en maquina Smith',
  'smith upright row': 'Remo al menton en maquina Smith',
  'smith wide grip bench press': 'Press de banca ancho en maquina Smith',
  'smith wide grip decline bench press': 'Press de banca ancho declinado en maquina Smith',
  'snatch pull': 'Jale de arrancada',
  'spell caster': 'Rotacion lateral con barra',
  'sphinx': 'Esfinge',
  'spider crawl push up': 'Flexion con escalada de arana',
  'spine stretch': 'Estiramiento de columna',
  'spine twist': 'Giro de columna',
  'split squats': 'Sentadillas split',
  'squat': 'Sentadilla',
  'squat jerk': 'Sentadilla con envion',
  'squat on bosu ball': 'Sentadilla en bosu',
  'squat to overhead reach': 'Sentadilla con alcance sobre la cabeza',
  'squat to overhead reach with twist': 'Sentadilla con alcance sobre la cabeza y giro',
  'stability ball crunch (full range hands behind head)': 'Crunch en fitball rango completo manos detras cabeza',
  'stalder press': 'Press Stalder',
  'standing archer': 'Arquero de pie',
  'standing behind neck press': 'Press por detras del cuello de pie',
  'standing calf raise (on a staircase)': 'Gemelo de pie en escalera',
  'standing calves': 'Gemelos de pie',
  'standing calves calf stretch': 'Estiramiento de gemelo de pie',
  'standing hamstring and calf stretch with strap': 'Estiramiento de isquiotibial y gemelo de pie con correa',
  'standing lateral stretch': 'Estiramiento lateral de pie',
  'standing pelvic tilt': 'Inclinacion pelvica de pie',
  'standing single leg curl': 'Curl femoral a una pierna de pie',
  'standing wheel rollerout': 'Rueda abdominal de pie',
  'star jump (male)': 'Salto estrella',
  'stationary bike run v. 3': 'Bicicleta estatica (v. 3)',
  'stationary bike walk': 'Pedaleo suave en bicicleta estatica',
  'step-up': 'Subida al banco',
  'straddle maltese': 'Cruz maltesa en abduccion',
  'straddle planche': 'Plancha en abduccion',
  'straight leg outer hip abductor': 'Abductor externo de cadera con pierna recta',
  'superman push-up': 'Flexion superman',
  'suspended abdominal fallout': 'Caida abdominal en suspension',
  'suspended push-up': 'Flexion en suspension',
  'suspended reverse crunch': 'Crunch inverso en suspension',
  'suspended row': 'Remo en suspension',
  'suspended split squat': 'Sentadilla split en suspension',
  'swimmer kicks v. 2 (male)': 'Patadas de nadador (v. 2)',
  'swing 360': 'Balanceo 360',
  // --- T ---
  'three bench dip': 'Fondo con tres bancos',
  'tire flip': 'Volteo de neumatico',
  'trap bar deadlift': 'Peso muerto con barra trampa',
  'triceps dip': 'Fondo de triceps',
  'triceps dip (bench leg)': 'Fondo de triceps con pierna en banco',
  'triceps dip (between benches)': 'Fondo de triceps entre bancos',
  'triceps dips floor': 'Fondos de triceps en suelo',
  'triceps extension': 'Extension de triceps',
  'triceps press': 'Press de triceps',
  'triceps stretch': 'Estiramiento de triceps',
  'tuck crunch': 'Crunch agrupado',
  'twin handle parallel grip lat pulldown': 'Jalon con doble mango agarre paralelo',
  'twist hip lift': 'Elevacion de cadera con giro',
  'twisted leg raise': 'Elevacion de piernas con giro',
  'twisted leg raise (female)': 'Elevacion de piernas con giro (mujer)',
  'two toe touch (male)': 'Toque de dos dedos del pie',
  // --- U ---
  'upper back stretch': 'Estiramiento de espalda superior',
  'upright row': 'Remo al menton',
  'upward facing dog': 'Perro mirando hacia arriba (yoga)',
  // --- V ---
  'v-sit on floor': 'V-sit en suelo',
  'vertical leg raise (on parallel bars)': 'Elevacion de piernas vertical en paralelas',
  // --- W ---
  'walk elliptical cross trainer': 'Eliptica',
  'walking high knees lunge': 'Zancada con rodilla alta caminando',
  'walking lunge': 'Zancada caminando',
  'walking on incline treadmill': 'Caminata en cinta inclinada',
  'walking on stepmill': 'Caminata en stepmill',
  'weighted bench dip': 'Fondo en banco con peso',
  'weighted close grip chin-up on dip cage': 'Dominada supina cerrada con peso en jaula',
  'weighted cossack squats (male)': 'Sentadilla cosaca con peso',
  'weighted crunch': 'Crunch con peso',
  'weighted decline sit-up': 'Abdominal declinado con peso',
  'weighted donkey calf raise': 'Gemelo burro con peso',
  'weighted drop push up': 'Flexion con caida y peso',
  'weighted front plank': 'Plancha frontal con peso',
  'weighted front raise': 'Elevacion frontal con peso',
  'weighted hanging leg-hip raise': 'Elevacion de piernas y cadera colgado con peso',
  'weighted hyperextension (on stability ball)': 'Hiperextension con peso en fitball',
  'weighted kneeling step with swing': 'Paso de rodillas con balanceo y peso',
  'weighted lunge with swing': 'Zancada con balanceo y peso',
  'weighted muscle up': 'Muscle-up con peso',
  'weighted muscle up (on bar)': 'Muscle-up en barra con peso',
  'weighted one hand pull up': 'Dominada a una mano con peso',
  'weighted overhead crunch (on stability ball)': 'Crunch sobre la cabeza en fitball con peso',
  'weighted pull-up': 'Dominada con peso',
  'weighted round arm': 'Brazo circular con peso',
  'weighted russian twist': 'Giro ruso con peso',
  'weighted russian twist (legs up)': 'Giro ruso con piernas arriba y peso',
  'weighted russian twist v. 2': 'Giro ruso con peso (v. 2)',
  'weighted seated bicep curl (on stability ball)': 'Curl de biceps sentado en fitball con peso',
  'weighted seated twist (on stability ball)': 'Giro sentado en fitball con peso',
  'weighted side bend (on stability ball)': 'Flexion lateral en fitball con peso',
  'weighted sissy squat': 'Sentadilla sissy con peso',
  'weighted squat': 'Sentadilla con peso',
  'weighted standing curl': 'Curl de pie con peso',
  'weighted standing hand squeeze': 'Apretón de mano de pie con peso',
  'weighted straight bar dip': 'Fondo en barra recta con peso',
  'weighted stretch lunge': 'Zancada con estiramiento y peso',
  'weighted svend press': 'Press Svend con peso',
  'weighted three bench dips': 'Fondo con tres bancos y peso',
  'weighted tricep dips': 'Fondos de triceps con peso',
  'weighted triceps dip on high parallel bars': 'Fondo de triceps en paralelas altas con peso',
  'wheel rollout': 'Rueda abdominal',
  'wheel run': 'Rueda en carrera',
  'wide grip pull-up': 'Dominada agarre ancho',
  'wide grip rear pull-up': 'Dominada trasera agarre ancho',
  'wide hand push up': 'Flexion con manos abiertas',
  'wide-grip chest dip on high parallel bars': 'Fondo de pecho agarre ancho en paralelas altas',
  'wind sprints': 'Sprints de viento',
  'world greatest stretch': 'El mejor estiramiento del mundo',
  'wrist circles': 'Circulos de muneca',
  'wrist rollerer': 'Rodillo de muneca',
};
